import React, { createContext, useContext, useState, ReactNode } from 'react';

export type LanguageCode = 'zh-TW' | 'en';

export interface Language {
  code: LanguageCode;
  name: string;
  flag: string;
}

export const LANGUAGES: Language[] = [
  { code: 'zh-TW', name: '繁體中文', flag: '🇹🇼' },
  { code: 'en', name: 'English', flag: '🇺🇸' }
];

interface LanguageContextType {
  currentLang: Language;
  setLanguage: (code: LanguageCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  'zh-TW': {
    'brand': 'NEO-GYM 競技健身房',
    'nav.home': '首頁',
    'nav.about': '關於我們',
    'nav.features': '特色',
    'nav.courses': '課程',
    'nav.coaching': '私人教練',
    'nav.schedule': '課表',
    'nav.locations': '分店',
    'nav.membership': '會籍方案',
    'nav.contact': '聯絡我們',
    'nav.login': '登入會員',
    'hero.title': '超越極限，定義自我',
    'hero.subtitle': '超越自我',
    'hero.description': '最頂尖的器材、極致的場域、專業的教練團隊，為您的進化而生。',
    'hero.start': '進入追蹤系統',
    'hero.explore': '領取免費體驗',
    'hero.contact': '聯絡專員諮詢',
    'features.title': '頂級運動設施',
    'features.tag': 'Prime Facilities',
    'features.cardio.title': '高階心肺區',
    'features.cardio.desc': '配備頂級跑步機與飛輪，支援即時數據同步。',
    'features.strength.title': '重型阻力區',
    'features.strength.desc': '多組深蹲架與專業健力器材，打造極致力量。',
    'features.functional.title': '多功能訓練',
    'features.functional.desc': '草皮區、雪橇、戰繩，提升功能性體能。',
    'schedule.title': '團體課程課表',
    'schedule.tag': 'Group Classes',
    'schedule.mon': 'Mon',
    'schedule.tue': 'Tue',
    'schedule.wed': 'Wed',
    'schedule.thu': 'Thu',
    'schedule.fri': 'Fri',
    'schedule.sat': 'Sat',
    'schedule.sun': 'Sun',
    'schedule.detail': '查看詳情',
    'schedule.booking': '立即預約課程',
    'schedule.success': '課程預約成功！',
    'locations.title': '全國連鎖據點',
    'locations.tag': 'Our Locations',
    'locations.search': '搜尋分店...',
    'locations.search_tips_prefix': '💡 建議搜尋：',
    'locations.no_results': '未找到符合搜尋條件的分店，請嘗試其他關鍵字 (例如：大安、內湖、新莊、台中、24H、皮拉提斯)',
    'locations.clear_search': '重設搜尋',
    'locations.visit': '預約免費參觀',
    'locations.full_schedule': '看完整課表',
    'coaching.title': '私人健身教練',
    'coaching.tag': 'Personal Training',
    'coaching.more': '了解更多',
    'coaching.find': '尋找私人教練',
    'coaching.reserve': '立即預約諮詢體驗',
    'footer.rights': '© 2026 NEO-GYM. 版權所有。',
    'common.name': '姓名',
    'common.phone': '電話',
    'common.email': 'Email',
    'common.submit': '確認送出',
    'common.close': '關閉',
    'common.name_placeholder': '例如：王小明',
    'common.phone_placeholder': '例如：0912-345-678',
    'common.email_placeholder': '例如：john@example.com',
    'schedule.booking_title': '填寫預約資訊',
    'schedule.booking_success': '課程預約成功！',
    'schedule.booking_received': '我們已收到您的預約申請。',
    'schedule.instructor': '授課教練',
    'schedule.level': '建議等級',
    'schedule.intro': '課程介紹',
    'locations.booking_title': '預約免費參觀',
    'locations.booking_success': '參觀預約成功！',
    'locations.booking_received': '專員將於 24 小時內與您聯繫。',
    'locations.details_btn': '查看分店詳情',
    'locations.facilities': '館內設施',
    'locations.contact_info': '聯絡資訊',
    'contact.form.subject_default': '領取免費 7 日體驗計畫',
    'contact.form.error': '發生錯誤，請稍後再試。',
    'contact.form.success_desc': '感謝您的諮詢，專人將盡快與您聯繫。',
    'contact.form.retry': '再傳送一則訊息',
    'social.title': '社交媒體',
    'social.owner': '公司負責人',
    'social.coach': '教練',
    'social.secretary1': '秘書一',
    'social.secretary2': '秘書二',
    'courses.reserve_btn': '立即預約',
    'success.before': 'Before',
    'success.after': 'After',
    'success.duration': '持續時間',
    'coaching.philosophy_title': '關於 NEO-GYM 私人教練',
    'coaching.why_title': '為什麼選擇私人教練？',
    'coaching.science_title': '科學化的訓練流程',
    'coaching.nutrition_title': '全方位的營養指導',
    'coaching.match_title': '尋找您的專屬教練',
    'coaching.category_strength': '力量增長組',
    'coaching.category_sculpt': '體態雕塑組',
    'coaching.category_health': '產後/健康組',
    'coaching.category_special': '專項運動強化',
    'coaching.select_title': '選擇您的教練',
    'coaching.back': '← 返回組別選擇',
    'coaching.note': '備註 / 需求 (選填)',
    'ai.title': 'AI 運動教練',
    'ai.empty': '有任何運動或健身問題嗎？儘管問我！對話將自動保存。',
    'ai.placeholder': '問問如何制定計畫或改善動作...',
    'ai.clear_confirm': '確定要清除所有聊天紀錄嗎？',
    'ai.clear_tooltip': '清除對話紀錄',
    'ai.error_response': '我現在無法回答這個問題，請稍候再試。',
    'ai.network_error': '抱歉，發生了錯誤。請檢查您的網路連線或稍後再試。',
    'ai.status': '隨時在線',
    'membership.title': '特選會籍方案',
    'membership.subtitle': '選擇最符合您目標的訓練計畫',
    'membership.monthly': '月',
    'membership.popular': '熱門選擇',
    'membership.starter_title': '基礎方案',
    'membership.starter_price': '600',
    'membership.starter_feat1': '依量計費彈性高',
    'membership.starter_feat2': '單次入場 150/次',
    'membership.starter_feat3': '適合偶爾運動的你',
    'membership.benefits.title': '會員專屬福利',
    'membership.benefits.feature1.title': '深層數據分析',
    'membership.benefits.feature1.desc': '詳細追蹤您的體脂、肌肉量與代謝趨勢，並由 AI 提供個人化建議。',
    'membership.benefits.feature2.title': '優先預約權',
    'membership.benefits.feature2.desc': '熱門團體課程與私人教室享有提前 7 天優先預約資格。',
    'membership.benefits.feature3.title': '專屬社群活動',
    'membership.benefits.feature3.desc': '參與每月舉辦的內部挑戰賽與健康講座，與其他強者交流。',
    'membership.benefits.feature4.title': '全台據點通用',
    'membership.benefits.feature4.desc': '白金會員可暢行全台所有 NEO-GYM 據點，運動不受限。',
    'membership.booking_title': '加入會員預約',
    'membership.booking_subtitle': '請填寫基本資訊，我們將有專員連繫您處理入會手續。',
    'membership.elite_title': '特選會籍方案',
    'membership.elite_price': '1,500',
    'membership.elite_feat1': '不限進場次數',
    'membership.elite_feat2': '首次需付入會費100元',
    'membership.elite_feat3': '自由訓練首選',
    'membership.pro_title': '合約會員',
    'membership.pro_price': '1,200',
    'membership.pro_feat1': '簽約一年',
    'membership.pro_feat2': '最具性價比的選擇',
    'membership.pro_feat3': '首次需付入會費100元',
    'membership.join_now': '立即預約',
    'landing.locations.label': '尋找據點',
    'location.xinzhuang.name': '新莊旗艦店',
    'location.xinzhuang.addr': '新北市新莊區中正路347巷10號B1',
    'location.xinzhuang.desc': '新莊最核心健身據點，引進原裝 Matrix 競技器材與專業 InBody 270 身體組成分析儀。擁有寬敞的多功能草皮區，滿足各種訓練需求。',
    'location.daan.name': '大安精品店',
    'location.daan.addr': '台北市大安區忠孝東路四段 88 號',
    'location.daan.desc': '頂級精品健身空間，專注於身心平衡與塑形。提供一對一皮拉提斯大器械教學，以及營養師調配的專屬能量飲品。',
    'location.neihu.name': '內湖科技店',
    'location.neihu.addr': '台北市內湖區瑞光路 500 號',
    'location.neihu.desc': '專為科技精英打造的 24 小時運動空間。擁有多元化重訓區與沉浸式飛輪投影教室，隨時滿足您的運動渴望。',
    'location.taichung.name': '台中新光店',
    'location.taichung.addr': '台中市西屯區台灣大道三段 301 號',
    'location.taichung.desc': '中台灣最大規模據點，擁有寬敞的戶外訓練區與草坪區。適合進行 CrossFit 與強人訓練，提供最硬派的鍛鍊環境。',
    'location.banqiao.name': '板橋雙十店',
    'location.banqiao.addr': '新北市板橋區雙十路二段100號',
    'location.banqiao.desc': '新北板橋精華核心區！全店配備頂級高規格無氧與有氧重訓器材，配有 24H 智慧感應手環進出，以及專屬草皮與戰繩區，給您最震撼的終極鍛鍊感受。',
    'location.linkou.name': '林口三井店',
    'location.linkou.addr': '新北市林口區文化三路一段50號',
    'location.linkou.desc': '位於林口三井 A9 精華地段。寬敞高挑落地窗，享受自然光灑落的運動視界。店內規劃頂級有氧跑步機、划船機，並設有頂級瑜珈與皮拉提斯教室。',
    'location.hsinchu.name': '新竹科學園區店',
    'location.hsinchu.addr': '新竹市東區介壽路18號',
    'location.hsinchu.desc': '專為竹科科技工程師與領袖精英量身定制！24小時不打烊，高規格引進美式經典純鐵重訓品牌，並附設專業乳清蛋白運動補給吧與放鬆舒壓區，助您平衡工作與強健體魄。',
    'location.kaohsiung.name': '高雄三多店',
    'location.kaohsiung.addr': '高雄市前鎮區三多三路213號',
    'location.kaohsiung.desc': '南台灣極致健身地標！座落於高雄三多商圈中心，超大挑高雙層訓練空間。備有高階多功能 CrossFit 綜合框架重訓區、室內跑道與專業冷療恢復池。',
    'location.tag.strength': '重訓區',
    'location.tag.grass': '廣大草皮',
    'location.tag.inbody': 'InBody',
    'location.tag.yoga': '瑜珈室',
    'location.tag.pilates': '皮拉提斯',
    'location.tag.coffee': '咖啡吧',
    'location.tag.24h': '24H',
    'location.tag.cycling': '飛輪教室',
    'location.tag.outdoor': '戶外訓練',
    'location.hours.24': '24小時營業',
    'locations.visit_booking': '免費預約參觀',
    'locations.redirect_note': '3 秒後自動跳轉...',
    'locations.detail_meta_title': 'NEO-GYM 據點詳情',
    'contact.info.address_val': '新北市新莊區中正路347巷10號B1',
    'contact.info.hours_val': '06:00 - 24:00 (每日)',
    'dashboard.explore': '探索會員專屬功能',
    'dashboard.premium_member': '白金會員',
    'dashboard.weekly_target': '每週目標',
    'dashboard.consistency': '持續天數',
    'dashboard.days': '天',
    'dashboard.new_record': '新紀錄！',
    'dashboard.kcal_burned': '本週已消耗 3,500 kcal',
    'tools.utilities': '健身工具組',
    'tools.bmi_result': '您的測量結果',
    'tools.height_placeholder': '例如：175',
    'tools.weight_placeholder': '例如：70',
    'tools.round_prefix': '第',
    'tools.round_suffix': '組 / 共',
    'tools.cups_suffix': '杯',
    'tools.progress': '目前進度',
    'schedule.group_classes': '團體課程詳情',
    'schedule.classes_count': '門課程',
    'membership.pricing_label': '方案訂價',
    'coaching.program_detail': '訓練課程詳情',
    'coaching.features_title': '課程特色',
    'coaching.info_title': '課程資訊',
    'coaching.selector_subtitle': '點擊教練頭像以查看詳細資訊並進行預約',
    'coaching.match_note': '點擊類別後，我們將根據您的需求推薦合適教練',
    'coaching.match_cta': '開始媒合專屬教練',
    'coaching.category_strength_desc': '適合想要大幅提升深蹲、硬舉實力，追求極致力量的您。',
    'coaching.category_sculpt_desc': '專注於肌肉線條、減脂優化，打造完美身材比例。',
    'coaching.category_health_desc': '溫和但有效的訓練，找回核心力量與基礎體能。',
    'coaching.category_special_desc': '針對棒球、高爾夫或馬拉松等專項運動，優化爆發力與耐力。',
    'coaching.why_desc': '私人教練不僅是指導動作，更是您的健康管理專家。透過精確的運動處方，我們能大幅縮短您的增肌減脂路徑，並確保每一次訓練的安全性。',
    'coaching.science_desc': '從基礎體態評估（FMS）、InBody 數據分析到目標設定，我們的課程皆以科學研究為基礎，量化您的進步幅度。',
    'coaching.nutrition_desc': '訓練佔 30%，飲食佔 70%。教練會協助您建立正確的飲食習慣，讓訓練效果從健身房延伸到您的餐桌。',
    'course.weight.title': '重量訓練課程',
    'course.weight.desc': '針對個人目標，從基礎動作優化到高階力量訓練。透過精確的負荷管理與姿勢監控，有效增加肌肉量、提升基礎代謝，打造強健體魄。',
    'course.weight.feat1': '基礎動作評估',
    'course.weight.feat2': '漸進式超負荷',
    'course.weight.feat3': '肌力與體態追蹤',
    'course.weight.feat4': '力量週期規劃',
    'course.weight.target': '增肌、減脂、提升力量',
    'course.relax.title': '肌肉放鬆課程',
    'course.relax.desc': '結合按摩球、滾筒與徒手伸展，針對運動後緊繃的肌群進行深層釋放。改善肌肉彈性、加速恢復速度，並預防潛在的運動傷害。',
    'course.relax.feat1': '筋膜放鬆技術',
    'course.relax.feat2': '關節活動度優化',
    'course.relax.feat3': '神經肌肉抑制法',
    'course.relax.feat4': '恢復性伸展',
    'course.relax.target': '肌肉痠痛恢復、預防傷害',
    'course.boxing.title': '拳擊訓練課程',
    'course.boxing.desc': '不僅是技術練習，更是一場高強度的間歇訓練。在教練指導下練習出拳、閃躲與腳步移動，同時大幅提升心肺功能與敏捷性。',
    'course.boxing.feat1': '基礎拳法教學',
    'course.boxing.feat2': '打擊靶具練習',
    'course.boxing.feat3': '核心旋轉力量',
    'course.boxing.feat4': '高強度心肺訓練',
    'course.boxing.target': '提升敏捷度、體力強化、紓壓',
    'course.vipr.title': 'ViPR訓練課程',
    'course.vipr.desc': '利用橡膠管（ViPR）進行全方位的負重移動訓練。將重量訓練與動作整合結合，非常適合提升生活機能與運動員專項能力。',
    'course.vipr.feat1': '全方位多面移動',
    'course.vipr.feat2': '整合性力量訓練',
    'course.vipr.feat3': '核心穩定性優化',
    'course.vipr.feat4': '功能性動作模式',
    'course.vipr.target': '提升身體協調、功能性肌力',
    'course.kettle.title': '壺鈴訓練課程',
    'course.kettle.desc': '專注於爆炸性力量與耐力的訓練。從基礎的 Swing 到進階的 Snatch，強化臀大肌與下背力量，打造極具爆發力的「運動員體質」。',
    'course.kettle.feat1': '鐘擺動力控制',
    'course.kettle.feat2': '髖部爆發力開發',
    'course.kettle.feat3': '單側力量穩定',
    'course.kettle.feat4': '高效率全身性燃脂',
    'course.kettle.target': '提升爆發力、核心穩定',
    'course.suspension.title': '懸吊訓練課程',
    'course.suspension.desc': '利用自身體重與不穩定性進行訓練。在繩索的帶動下，每一秒都在考驗核心的穩定性與肌群的協調能力，適合各種程度的訓練者。',
    'course.suspension.feat1': '核心肌群全程參與',
    'course.suspension.feat2': '不穩定平面訓練',
    'course.suspension.feat3': '角度可調強度',
    'course.suspension.feat4': '全身性肌力發展',
    'course.suspension.target': '核心強化、身形雕塑',
    'course.functional.title': '多功能訓練課程',
    'course.functional.desc': '打破單一器材的限制，將戰繩、藥球、雪橇等多元工具整合。提升身體的綜合運動素養，讓健身不再單調、更具挑戰性。',
    'course.functional.feat1': '多樣化訓練教具',
    'course.functional.feat2': '不同能量系統訓練',
    'course.functional.feat3': '敏捷與平衡挑戰',
    'course.functional.feat4': '團隊競技或個人紀錄',
    'course.functional.target': '全面運動素質提升',
    'coach.marcus.spec': 'SBD 專項、爆發力訓練',
    'coach.jessica.spec': '女性體態雕塑、增肌減脂',
    'coach.david.spec': '健力、肌力與體能',
    'coach.sarah.spec': '產後恢復、高齡運動',
    'coach.kevin.spec': '專項運動員體能、棒球體能',
    'coach.elena.spec': '皮拉提斯整合訓練、曲線營造',
    'coach.alex.spec': '強力健美、極限肌力',
    'coach.mina.spec': '健美小姐曲線對稱、姿態校正',
    'coach.leo.spec': '鐵人三項體力配置、高階耐力訓練',
    'coach.sophia.spec': '銀髮族體能發展、康復指導',
    'coach.james.spec': '極限特務體能、近身格鬥',
    'coach.crofts.spec': '探險專項體能、生存訓練',
    'games.hurdles.name': '定向障礙賽',
    'games.hurdles.instructions': '使用方向鍵 ↑ ↓ ← → 躲避障礙！',
    'games.hurdles.static': '靜態障礙',
    'games.hurdles.moving': '動態障礙',
    'games.hurdles.enter': '進入賽場',
    'games.hurdles.select_level': '選擇難度等級',
    'games.hurdles.level_easy': '初階：慢步',
    'games.hurdles.level_medium': '中階：疾走',
    'games.hurdles.level_hard': '高階：狂奔',
    'games.hurdles.desc_easy': '障礙物較少，速度緩慢',
    'games.hurdles.desc_medium': '障礙物密集，包含動態陷阱',
    'games.hurdles.desc_hard': '極限挑戰，考驗反應速度',
    'games.hurdles.retry': '重新開始',
    'games.hurdles.again': '再賽一場',
    'games.hurdles.controls': '使用鍵盤 WASD / 方向鍵 或 點擊控制',
    'games.sprint.stadium': '田徑競技場',
    'games.sprint.champion': '你是冠軍！',
    'games.sprint.keep_running': '再接再厲！',
    'games.sprint.go': '出發！',
    'games.sprint.finish': '終點！',
    'games.sprint.crashed': '撞到了！',
    'membership.inbody_title': 'InBody 體成份測量',
    'membership.inbody.details_title': '身體組成詳細分析',
    'membership.inbody_price': '100 / 次',
    'membership.inbody_desc': '採用 InBody 270 專業設備，提供全方位的身體數據分析，助您精確掌握訓練成效。',
    'membership.inbody.fat': '體脂率',
    'membership.inbody.fat_val': '分段分析',
    'membership.inbody.muscle': '骨骼肌重',
    'membership.inbody.muscle_val': '核心追蹤',
    'membership.inbody.metabolism': '基礎代謝率',
    'membership.inbody.metabolism_val': 'BMR 評估',
    'membership.inbody.balance': '身體平衡',
    'membership.inbody.balance_val': '左右均衡',
    'membership.inbody.visceral': '內臟脂肪',
    'membership.inbody.visceral_val': '健康指標',
    'membership.inbody.water': '體水份量',
    'membership.inbody.water_val': '水合分析',
    'membership.inbody.bmc': '骨礦物質',
    'membership.inbody.bmc_val': '骨質密度',
    'membership.inbody.bmi': 'BMI 指數',
    'membership.inbody.bmi_val': '質量指數',
    'membership.inbody.fat_desc': '體脂率反映脂肪佔體重的百分比。正常比例有助於保護內臟及維持賀爾蒙平衡。',
    'membership.inbody.muscle_desc': '骨骼肌重是維持代謝與爆發力的關鍵。增加肌肉量能提升基礎代謝率（BMR）。',
    'membership.inbody.metabolism_desc': 'BMR 指的是維持維生功能所需的能量。數值越高，越不容易囤積脂肪。',
    'membership.inbody.balance_desc': '評估身體左右肢段的肌肉分佈，幫助找出發力不均與代償問題。',
    'membership.inbody.visceral_desc': '內臟脂肪量過高與心血管疾病風險正相關。此數據是長期健康監控的重點。',
    'membership.inbody.water_desc': '確保身體不處於脫水狀態。足夠的水分對肌肉修復與營養輸送至關重要。',
    'membership.inbody.bmc_desc': '評估身體骨骼中的礦物質含量，與骨骼強度及未來骨鬆風險評估有關。',
    'membership.inbody.bmi_desc': '雖然無法區分肌肉與脂肪，但仍是國際通用的身體質量初步評估指標。',
    'dashboard.tag': '智慧生態系統',
    'dashboard.title': '追蹤您的進化',
    'dashboard.desc': '透過先進的追蹤系統，即時洞察您的運動表現。同步訓練數據、監控進度，每週突破個人最佳紀錄。',
    'dashboard.stat1.title': '即時數據統計',
    'dashboard.stat1.desc': '即時查看您的心率與熱量消耗。',
    'dashboard.stat2.title': '目標導向計畫',
    'dashboard.stat2.desc': '設定每週目標，並在接近達成時收到提醒。',
    'story.result.weightloss': '成功減重',
    'story.result.fitness': '體能提升',
    'story.result.painfree': '告別日常酸痛',
    'story.result.recomp': '體態重塑',
    'story.stat.months': '個月',
    'story.stat.year': '年',
    'story.stat.beginner': '初學者',
    'story.stat.runner': '跑者',
    'story.stat.sedentary': '久坐族',
    'story.stat.active': '活力派',
    'dashboard.stat3.title': '成就獎勵系統',
    'dashboard.stat3.desc': '贏得勳章並在本地排行榜上名列前茅。',
    'dashboard.stat4.title': '連續達成追蹤',
    'dashboard.stat4.desc': '透過連續運動獎勵，保持訓練動力。',
    'dashboard.chart.title': '熱量消耗趨勢',
    'dashboard.chart.subtitle': 'CALORIE CONSUMPTION TREND',
    'dashboard.chart.total': '7日累計大卡',
    'tools.title': '健身輔助工具',
    'tools.bmi_title': 'BMI 計算機',
    'tools.bmi_subtitle': '體態評估',
    'tools.hiit_title': 'HIIT 計時器',
    'tools.hiit_subtitle': '間歇訓練',
    'tools.water_title': '每日飲水',
    'tools.water_subtitle': '水分追蹤',
    'tools.height': '身高 (cm)',
    'tools.weight': '體重 (kg)',
    'tools.calculate_bmi': '計算 BMI 指數',
    'tools.bmi_underweight': '體重過輕',
    'tools.bmi_normal': '正常範圍',
    'tools.bmi_overweight': '過重',
    'tools.bmi_obese1': '輕度肥胖',
    'tools.bmi_obese2': '中度肥胖',
    'tools.bmi_obese3': '重度肥胖',
    'tools.work': '工作 (秒)',
    'tools.rest': '休息 (秒)',
    'tools.rounds': '組數',
    'tools.working': '🔥🔥 運動中',
    'tools.resting': '🧊🧊 休息中',
    'tools.water_goal_desc': '建議每日攝取 2000ml 以上的水分 (約 8 杯)',
    'tools.water_achieved': '目標達成！今日水分充沛 💧',
    'tools.water.calculate': '計算個人飲水需求',
    'tools.water.formula_desc': '您的專屬目標為體重 (kg) × 35 ml',
    'tools.water.calc_result_prefix': '您的每日建議飲水量為 ',
    'tools.water.calc_result_suffix': 'ml (約 {cups} 杯 250ml)',
    'tools.water.reset_calc': '重新計算',
    'tools.workout_title': 'AI 健身課表',
    'tools.workout_subtitle': '智慧生成',
    'tools.workout_generator_title': 'AI 健身課表生成器',
    'tools.workout_generator_desc': '根據您的目標與現有設備，即時打造個人化訓練內容。',
    'tools.workout_label_goal': '訓練目標',
    'tools.workout_label_level': '您的程度',
    'tools.workout_label_equipment': '可用設備',
    'tools.workout_btn_generate': '生成課表',
    'tools.workout_btn_generating': '生成中...',
    'tools.workout_coach_note': 'AI 個人教練建議',
    'tools.workout_placeholder_title': '等待參數輸入',
    'tools.workout_placeholder_desc': '選擇您的目標並點擊生成',
    'tools.workout.goal_muscle': '增肌',
    'tools.workout.goal_fat': '減脂',
    'tools.workout.goal_strength': '提升力量',
    'tools.workout.goal_health': '身體健康',
    'tools.workout.level_beginner': '初學者',
    'tools.workout.level_intermediate': '中級',
    'tools.workout.level_advanced': '高級',
    'tools.workout.eq_dumbbell': '啞鈴',
    'tools.workout.eq_barbell': '槓鈴',
    'tools.workout.eq_cable': '滑輪機',
    'tools.workout.eq_kettlebell': '壺鈴',
    'tools.workout.eq_pullup': '單槓',
    'tools.workout.eq_bodyweight': '徒手',
    'games.sprint.instructions': '交替連打 A/D 啟動衝刺！與五位頂尖 AI 同場競技，體驗不同賽程的極致爆發。現在支援 100m 與 200m 距離。',
    'games.sprint.enter': '進入備戰',
    'games.sprint.classic': '經典霓虹',
    'games.sprint.volcano': '熔岩荒原',
    'games.sprint.jungle': '網絡叢林',
    'games.sprint.deepsea': '深海壓力',
    'games.sprint.back_main': '返回主選單',
    'games.sprint.sprint_100': '極速衝刺',
    'games.sprint.sprint_200': '耐力爆發',
    'games.sprint.reselect_env': '重新選擇環境',
    'games.sprint.again': '再賽一場',
    'games.sprint.runner': 'AI 跑者',
    'success.title': '學員蛻變見證',
    'success.details_title': '學員蛻變詳情',
    'success.cta': '我也要預約體驗計畫',
    'contact.title': '聯絡我們',
    'contact.subtitle': '準備好開始您的強者之路了嗎？留下聯絡資訊，我們的顧問將在 24 小時內與您聯繫。',
    'contact.form.name': '中文姓名',
    'contact.form.phone': '聯絡電話',
    'contact.form.email': '電子郵件',
    'contact.form.subject': '諮詢主題',
    'contact.form.message': '訊息內容',
    'contact.form.submit': '傳送諮詢訊息',
    'contact.form.success': '訊息已成功傳送',
    'contact.info.address': '公司地址',
    'contact.info.phone': '諮詢專線',
    'contact.info.email': '電子郵件',
    'contact.info.hours': '服務時間',
    'courses.title': '專業訓練課程',
    'courses.subtitle': '根據您的目標，提供多樣化的高強度課程，從核心雕塑到爆發力提升，全面釋放潛能。',
    'courses.target_group': '針對族群',
    'courses.goals_title': '課程目標',
    'courses.details_title': '課程詳情',
    'courses.duration_label': '預計時長：',
    'courses.book_now': '立即預約體驗',
    'schedule.morning_flow': '晨間流動瑜珈',
    'schedule.spinning': '極速飛輪',
    'schedule.mma': '綜合格鬥 (MMA)',
    'schedule.trx': 'TRX 全身訓練',
    'schedule.foam_roll': '滾筒筋膜放鬆',
    'schedule.bootcamp': '早安戰鬥營',
    'schedule.core_base': '核心強化基礎',
    'schedule.noon_strength': '午間肌力強化',
    'schedule.yin_yoga': '舒心陰瑜珈',
    'schedule.zumba': 'Zumba 派對',
    'schedule.reformer': '器械皮拉提斯',
    'schedule.hiit_burn': 'HIIT 燃脂極限',
    'schedule.boxing_base': '現代拳擊基礎',
    'schedule.functional_challenge': '功能性體能挑戰',
    'schedule.sound_healing': '正念音療瑜珈',
    'schedule.barbell_strength': '重量槓鈴訓練',
    'schedule.tabata_flash': 'Tabata 快閃課',
    'schedule.muay_thai': '泰拳基礎與防衛',
    'schedule.air_yoga': '空中瑜珈雕塑',
    'schedule.leg_sculpt': '放鬆拉筋美腿',
    'schedule.dawn_flow': '晨曦能量瑜珈',
    'schedule.kettlebell': '壺鈴肌耐力',
    'schedule.krav_maga': '以色列防身術',
    'schedule.glow_cycle': '夜間螢光飛輪',
    'schedule.aroma_yoga': '芳療香氛瑜珈',
    'schedule.warrior_camp': '週末戰士訓練營',
    'schedule.balance_core': '動態核心與平衡',
    'schedule.air_stretch': '反重力伸展實作',
    'schedule.bjj': '巴西柔術基礎',
    'schedule.twilight_meditation': '暮光靜心冥想',
    'schedule.morning_dance': '早安熱舞挑戰',
    'schedule.body_recovery': '全身功能修復',
    'schedule.kpop_dance': 'K-Pop 舞蹈派對',
    'schedule.rucking': '負重遠行探索',
    'schedule.muscle_balance': '肌肉平衡與評估',
    'schedule.level_all': '各等級皆可',
    'schedule.level_beginner': '入門',
    'schedule.level_intermediate': '中階',
    'schedule.level_advanced': '進階',
    'schedule.tag_relaxation': '放鬆身心',
    'schedule.tag_cardio': '有氧心肺',
    'schedule.tag_combat': '格鬥對抗',
    'schedule.tag_strength': '力量訓練',
    'schedule.tag_recovery': '肌肉修復',
    'schedule.tag_intensity': '高強度',
    'schedule.tag_core': '核心強化',
    'schedule.tag_dance': '舞蹈派對',
    'schedule.tag_wellness': '健康管理',
    'schedule.tag_fitness': '體能挑戰',
    'schedule.tag_flexibility': '柔軟度',
    'schedule.tag_flow': '流動藝術',
    'schedule.tag_defense': '防身技術',
    'schedule.tag_challenge': '極限挑戰',
    'schedule.tag_air_yoga': '空中瑜珈',
    'schedule.tag_peace': '靜謐冥想',
    'schedule.tag_fun': '趣味運動',
    'schedule.tag_outdoor': '戶外探索',
    'schedule.tag_consult': '體態諮詢',
    'schedule.cat_hiit': '高強度間歇',
    'schedule.cat_dance': '炫彩舞蹈',
    'schedule.cat_wellness': '身心靈平衡',
    'schedule.morning_flow.desc': '溫和地喚醒身體，透過呼吸與流動的動作，為一天注入平靜與活力。',
    'schedule.spinning.desc': '跟著節奏跳動，在高強度的踩踏中燃燒脂肪，提升心肺功能與腿部耐力。',
    'schedule.mma.desc': '結合拳擊、泰拳與摔跤技巧，提升身體協調性、爆發力與基礎防身能力。',
    'schedule.trx.desc': '利用懸吊系統進行全身性阻力訓練，同時挑戰肌力與核心穩定性。',
    'schedule.foam_roll.desc': '針對全天運動後的肌肉進行深層釋放，改善柔軟度並預防潛在傷害。',
    'schedule.bootcamp.desc': '專為晨型人設計的高強度訓練，結合間歇運動與自重訓練，快速啟動一整天的代謝。',
    'schedule.core_base.desc': '專注於深層核心肌群的穩定與訓練，改善姿勢並提升身體機能。',
    'schedule.noon_strength.desc': '針對核心與大肌群進行針對性訓練，適合利用午休時間提升代謝與力量。',
    'schedule.yin_yoga.desc': '透過長時間的停留與靜心，針對關節與深層組織進行調節與放鬆。',
    'schedule.zumba.desc': '充滿熱情的拉丁舞蹈節奏，讓你在快樂的氣氛中達到全身性的燃脂運動。',
    'schedule.reformer.desc': '結合專業器械，精準訓練核心肌群，同步優化身體线条與活動度。',
    'schedule.hiit_burn.desc': '極短時間內透過高低強度交替，挑戰體能極限，達到後燃效應的最大化。',
    'schedule.boxing_base.desc': '學習正確的擊拳動作與步法，在熱血沸騰的打擊感中舒壓並提升心肺。',
    'schedule.functional_challenge.desc': '模擬日常生活動作進行綜合訓練，全面強化爆發力、速度與靈活度。',
    'schedule.sound_healing.desc': '結合頌缽音療與溫和伸展，深層淨化心靈，釋放日常累積的隱形壓力。',
    'schedule.barbell_strength.desc': '科學化的負重訓練，幫助建立紮實的肌肉量，提高基礎代謝並美化曲線。',
    'schedule.tabata_flash.desc': '高效利用20秒訓練10秒休息的公式，在短時間內爆發最高能量產出。',
    'schedule.muay_thai.desc': '拳、腿、肘、膝的全方位運作，體驗泰拳的力與美，同時鍛鍊反應力。',
    'schedule.air_yoga.desc': '利用掛布輔助，在反重力的環境下挑戰核心力量與身體平衡感。',
    'schedule.leg_sculpt.desc': '專注於下肢的長時伸展，有效消除水腫，塑造匀稱修長的腿部線條。',
    'schedule.dawn_flow.desc': '與第一道晨光共同起舞，在大跨度的動作中拉伸全身，激發一整天的創造力。',
    'schedule.kettlebell.desc': '整合性全身發力訓練，透過壺鈴擺盪與推舉，提升身體穩定性。',
    'schedule.krav_maga.desc': '實戰導望的動態防衛技巧，在模擬情境中學習如何快速應對潛在威脅。',
    'schedule.glow_cycle.desc': '重低音聲光衝擊！在充滿熱店氛圍的環境中，忘卻疲憊，燃燒脂肪。',
    'schedule.aroma_yoga.desc': '結合頂級植物精油療癒，沈浸在香氛中徹底放鬆，為週末揭開序幕。',
    'schedule.warrior_camp.desc': '一場硬派的體力馬拉松！針對爆發力、耐力與意志力進行全方位磨鍊。',
    'schedule.balance_core.desc': '透過多平面動作設計，挑戰大腦與神經對身體和核心的精確掌控。',
    'schedule.air_stretch.desc': '低空懸吊輔助，深入骨骼與關節間隙的精細拉伸，體驗前所未有的舒展感。',
    'schedule.bjj.desc': '以柔克剛的高端藝術。學習地板技與關節技，大幅提升身體感官與智謀。',
    'schedule.twilight_meditation.desc': '日落時分的集體冥想，與大自然的脈動同步，重塑身心的深層和諧。',
    'schedule.morning_dance.desc': '結合現代舞與流行節奏，在充滿動感的氛圍中開啟悠閒的週日早晨。',
    'schedule.body_recovery.desc': '針對一週訓練後的疲勞累積，透過專業工具輔助進行全身性的功能修整。',
    'schedule.kpop_dance.desc': '學習當紅韓團舞曲亮點，即使沒有舞蹈基礎也能在音樂中大展身手。',
    'schedule.rucking.desc': '模擬野外負重行軍，強化核心耐力與基礎生理強度，適合愛愛好戶外的妳。',
    'schedule.muscle_balance.desc': '團體式的體態篩查與糾正，找出你身體的弱連結，並學會如何優化。',
    'schedule.capacity': '剩餘名額',
    'games.hurdles.goal': '成功達陣！',
    'games.hurdles.points': '積分',
    'games.sprint.select_env': '選擇比賽場景',
    'games.sprint.select_dist': '選擇競賽距離',
    'games.sprint.time': '本次用時',
    'games.sprint.score': '戰鬥評分',
    'games.sprint.you': '你',
    'landing.hero.subtitle': '專業體能訓練工作室',
    'landing.courses.featured': '精選私人課程',
    'landing.stories.title': '成功見證',
    'landing.stories.subtitle': '我們的隊員在教練指導下取得的驚人進步。',
    'landing.stories.details_title': '蛻變細節',
    'landing.stories.before': '訓練前',
    'landing.stories.after': '訓練後',
    'landing.stories.duration': '持續時間',
    'landing.stories.cta': '我也要開始蛻變',
    'landing.contact.featured': '聯繫我們',
    'landing.newsletter.title': '加入我們的運動',
    'landing.newsletter.subtitle': '訂閱我們的通訊，獲取獨家訓練技巧、營養指南和社群活動更新。',
    'landing.newsletter.placeholder': '您的電子郵件...',
    'landing.newsletter.subscribe': '立即訂閱',
    'landing.newsletter.spam_note': '絕無垃圾郵件。隨時可以取消訂閱。',
    'course.sculpt.title': '極致健體雕塑',
    'course.sculpt.category': '肌力訓練',
    'course.sculpt.price': 'NT$ 1,200 / 堂',
    'course.sculpt.target': '追求極致肌肉線條、想要增肌減脂或備賽需要的學員。',
    'course.sculpt.goal1': '增加肌肉肥大',
    'course.sculpt.goal2': '精準局部雕塑',
    'course.sculpt.goal3': '提升基礎代謝',
    'course.sculpt.content': '採用科學載荷遞增法，針對特定肌群進行深層刺激。課程包含精密的力量評估與動作矯正，確保每一份汗水都轉化為視覺上的震撼改變。',
    'course.sculpt.duration': '60 min',
    'course.burn.title': '高效燃脂循環',
    'course.burn.category': '心肺耐力',
    'course.burn.price': 'NT$ 1,000 / 堂',
    'course.burn.target': '希望在短時間內消耗大量熱量、提升心肺功能者。',
    'course.burn.goal1': '極致燃脂',
    'course.burn.goal2': '提升心肺耐力',
    'course.burn.goal3': '改善運動表現',
    'course.burn.content': '結合高強度間歇訓練 (HIIT) 與功能性動作。透過不間斷的動作組合，讓身體在課後持續產生「後燃效應」，是追求減重效果的首選課程。',
    'course.burn.duration': '50 min',
    'course.core.title': '核心穩定強化',
    'course.core.category': '功能訓練',
    'course.core.price': 'NT$ 1,100 / 堂',
    'course.core.target': '長期久坐、姿勢不良或希望提升運動穩定性的學員。',
    'course.core.goal1': '預防運動傷害',
    'course.core.goal2': '改善體態姿勢',
    'course.core.goal3': '強化深層核心',
    'course.core.content': '專注於脊椎穩定與多平面動作控制。透過皮拉提斯、核心滑盤與懸吊設備，找回身體失落的連結，打造強韌且穩定的身體基石。',
    'course.core.duration': '50 min',
    'story.lin.name': '林先生',
    'story.lin.story': '在 NEO-GYM 訓練 6 個月，成功減重 15 公斤並增加 5 公斤肌肉。',
    'story.lin.details': '林先生原本因為工作忙碌忽略健康，身體檢查出現多項紅字。在教練引導下，從每週兩次重訓開始，配合精密飲食控制，不僅體態改變，體力也有顯著提升。',
    'story.chang.name': '蓮小姐',
    'story.chang.story': '在 NEO-GYM 訓練 12 個月，體重減少 3 公斤並成功挑戰首場半程馬拉松。',
    'story.chang.details': '蓮小姐原本對體能沒自信且畏懼健身。在教練引導下，從核心基礎與心肺耐力循序開發，不僅成功減重，更找回挑戰自我極限的勇氣。趣味課程讓每一步都充滿動力。',
    'story.wang.name': '王先生',
    'story.wang.story': '在 NEO-GYM 訓練 8 個月，成功減重 6 公斤並徹底解決長期下背痛困擾。',
    'story.wang.details': '王先生原本深受工程師職業病「下背痛」困擾。在教練引導下，透過紅繩與功能性訓練強化核心深層肌群，不僅痛楚消失，原本受限的腰部活動度也有了顯著提升。',
    'story.lee.name': '李小姐',
    'story.lee.story': '在 NEO-GYM 訓練 10 個月，體脂率降低 8%，成功重塑產後緊緻體態。',
    'story.lee.details': '李小姐原本為產後體態與自信低潮所苦。在教練與營養諮詢雙管齊下，掌握能量代謝與正確飲食法，不僅身形視覺減一號，其代謝能力與精神狀態也更勝產前。',
  },
  'en': {
    'brand': 'NEO-GYM Pro Fitness',
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.features': 'Features',
    'nav.courses': 'Courses',
    'nav.coaching': 'Coaching',
    'nav.schedule': 'Schedule',
    'nav.locations': 'Locations',
    'nav.membership': 'Membership',
    'nav.contact': 'Contact',
    'nav.login': 'Login',
    'hero.title': 'BREAK LIMITS, DEFINE SELF',
    'hero.subtitle': 'EXCEED YOURSELF',
    'hero.description': 'Top-tier equipment, ultimate spaces, professional coaches, born for your evolution.',
    'hero.start': 'Start Tracking',
    'hero.explore': 'Free Trial',
    'hero.contact': 'Contact Counselor',
    'features.title': 'Prime Facilities',
    'features.tag': 'Prime Facilities',
    'features.cardio.title': 'Advanced Cardio',
    'features.cardio.desc': 'Top-tier treadmills and bikes with real-time data sync.',
    'features.strength.title': 'Heavy Resistance',
    'features.strength.desc': 'Multiple squat racks and professional powerlifting gear.',
    'features.functional.title': 'Functional Training',
    'features.functional.desc': 'Turf, sleds, and battle ropes for functional fitness.',
    'schedule.title': 'Class Schedule',
    'schedule.tag': 'Group Classes',
    'schedule.mon': 'Mon',
    'schedule.tue': 'Tue',
    'schedule.wed': 'Wed',
    'schedule.thu': 'Thu',
    'schedule.fri': 'Fri',
    'schedule.sat': 'Sat',
    'schedule.sun': 'Sun',
    'schedule.detail': 'View Details',
    'schedule.booking': 'Book Class Now',
    'schedule.success': 'Booking Successful!',
    'locations.title': 'Nationwide Branch',
    'locations.tag': 'Our Locations',
    'locations.search': 'Search branches...',
    'locations.search_tips_prefix': '💡 Suggested:',
    'locations.no_results': 'No branches found matching your search. Try other keywords (e.g., Daan, Neihu, Xinzhuang, Taichung, 24H, Pilates)',
    'locations.clear_search': 'Reset Search',
    'locations.visit': 'Book Free Visit',
    'locations.full_schedule': 'Full Schedule',
    'coaching.title': 'Private Coaching',
    'coaching.tag': 'Personal Training',
    'coaching.more': 'Learn More',
    'coaching.find': 'Find a Coach',
    'coaching.reserve': 'Reserve Consultation',
    'footer.rights': '© 2026 NEO-GYM. All rights reserved.',
    'common.name': 'Name',
    'common.phone': 'Phone',
    'common.email': 'Email',
    'common.submit': 'Submit',
    'common.close': 'Close',
    'common.name_placeholder': 'Ex: John Doe',
    'common.phone_placeholder': 'Ex: +1 234 567 890',
    'common.email_placeholder': 'Ex: john@example.com',
    'schedule.booking_title': 'Booking Information',
    'schedule.booking_success': 'Class Booked Successfully!',
    'schedule.booking_received': 'We have received your booking request.',
    'schedule.instructor': 'Instructor',
    'schedule.level': 'Level',
    'schedule.intro': 'Introduction',
    'locations.booking_title': 'Book a Free Visit',
    'locations.booking_success': 'Visit Booked Successfully!',
    'locations.booking_received': 'Our specialist will contact you within 24 hours.',
    'locations.details_btn': 'View Branch Details',
    'locations.facilities': 'Facilities',
    'locations.contact_info': 'Contact Info',
    'contact.form.subject_default': 'Get Free 7-Day Experience',
    'contact.form.error': 'An error occurred, please try again later.',
    'contact.form.success_desc': 'Thank you for your inquiry, our specialist will contact you soon.',
    'contact.form.retry': 'Send another message',
    'social.title': 'Social Media',
    'social.owner': 'Owner',
    'social.coach': 'Coach',
    'social.secretary1': 'Secretary 1',
    'social.secretary2': 'Secretary 2',
    'courses.reserve_btn': 'Reserve Now',
    'success.before': 'Before',
    'success.after': 'After',
    'success.duration': 'Duration',
    'coaching.philosophy_title': 'About NEO-GYM Private Coaching',
    'coaching.why_title': 'Why Choose Private Coaching?',
    'coaching.science_title': 'Scientific Training Process',
    'coaching.nutrition_title': 'Comprehensive Nutrition Guidance',
    'coaching.match_title': 'Find Your Specialist Coach',
    'coaching.category_strength': 'Strength Building',
    'coaching.category_sculpt': 'Body Sculpting',
    'coaching.category_health': 'Postnatal/Health',
    'coaching.category_special': 'Sports Performance',
    'coaching.select_title': 'Select Your Coach',
    'coaching.back': '← Back to categories',
    'coaching.note': 'Note / Requirements (Optional)',
    'ai.title': 'AI Fitness Coach',
    'ai.empty': 'Any fitness questions? Ask me! Conversations are saved automatically.',
    'ai.placeholder': 'Ask about plans or techniques...',
    'ai.clear_confirm': 'Are you sure you want to clear all chat history?',
    'ai.clear_tooltip': 'Clear chat history',
    'ai.error_response': 'I cannot answer this question right now, please try again later.',
    'ai.network_error': 'Sorry, an error occurred. Please check your connection or try again later.',
    'ai.status': 'Always Online',
    'membership.title': 'Membership Plans',
    'membership.subtitle': 'Choose the plan that fits your goals',
    'membership.monthly': 'mo',
    'membership.popular': 'Popular',
    'membership.starter_title': 'Hourly Plan',
    'membership.starter_price': '2 / Hour',
    'membership.starter_feat1': 'No time pressure',
    'membership.starter_feat2': 'Flexible usage',
    'membership.starter_feat3': 'Perfect for casual users',
    'membership.benefits.title': 'Member Benefits',
    'membership.benefits.feature1.title': 'Advanced Analytics',
    'membership.benefits.feature1.desc': 'Deep track of Body Fat, Muscle Mass and Metabolic trends with AI insights.',
    'membership.benefits.feature2.title': 'Priority Booking',
    'membership.benefits.feature2.desc': 'Get 7-day priority access to popular group classes and private studios.',
    'membership.benefits.feature3.title': 'Exclusive Community',
    'membership.benefits.feature3.desc': 'Join monthly internal challenges and health seminars with other athletes.',
    'membership.benefits.feature4.title': 'All Location Access',
    'membership.benefits.feature4.desc': 'Platinum members can access all NEO-GYM locations nationwide.',
    'membership.booking_title': 'Membership Application',
    'membership.booking_subtitle': 'Please fill in your info, and our team will contact you to finalize the process.',
    'membership.elite_title': 'Monthly Plan',
    'membership.elite_price': '1,500',
    'membership.elite_feat1': 'Unlimited Access',
    'membership.elite_feat2': '$5 Signup fee applies',
    'membership.elite_feat3': 'Best for consistent training',
    'membership.pro_title': 'Contract Member',
    'membership.pro_price': '1,200',
    'membership.pro_feat1': 'One year commitment',
    'membership.pro_feat2': 'Most economical choice',
    'membership.pro_feat3': '$5 Signup fee applies',
    'membership.join_now': 'Join Now',
    'landing.locations.label': 'Find a Club',
    'location.xinzhuang.name': 'Xinzhuang Flagship',
    'location.xinzhuang.addr': 'B1, No. 10, Ln. 347, Zhongzheng Rd., Xinzhuang Dist., New Taipei City',
    'location.xinzhuang.desc': 'The core fitness hub of Xinzhuang, featuring Matrix equipment and InBody 270. Spacious multi-functional turf area for all needs.',
    'location.daan.name': 'Daan Boutique',
    'location.daan.addr': 'No. 88, Sec. 4, Zhongxiao E. Rd., Daan Dist., Taipei City',
    'location.daan.desc': 'Premium boutique space focused on mind-body balance. One-on-one Reformer Pilates and specialized post-workout energy drinks.',
    'location.neihu.name': 'Neihu Tech',
    'location.neihu.addr': 'No. 500, Ruiguang Rd., Neihu Dist., Taipei City',
    'location.neihu.desc': '24/7 fitness space designed for tech professionals. Features diverse strength areas and immersive cycling classes.',
    'location.taichung.name': 'Taichung Shinkong',
    'location.taichung.addr': 'No. 301, Sec. 3, Taiwan Blvd., Xitun Dist., Taichung City',
    'location.taichung.desc': 'Largest branch in Central Taiwan with an outdoor training area and turf. Perfect for CrossFit and Strongman training.',
    'location.banqiao.name': 'Banqiao Double-Decade',
    'location.banqiao.addr': 'No. 100, Sec. 2, Shuangshi Rd., Banqiao Dist., New Taipei City',
    'location.banqiao.desc': 'Core district of Banqiao! Equipped with top-tier anaerobic and aerobic training machines, 24/7 smart wristband access, dedicated turf, and battle ropes for ultimate high-intensity workouts.',
    'location.linkou.name': 'Linkou Mitsui',
    'location.linkou.addr': 'No. 50, Sec. 1, Wenhua 3rd Rd., Linkou Dist., New Taipei City',
    'location.linkou.desc': 'Located in the prime Mitsui A9 area of Linkou. Spacious high-ceiling floor-to-ceiling windows with abundant natural light. Features premium aerobic treadmills, rowing machines, yoga, and Pilates facilities.',
    'location.hsinchu.name': 'Hsinchu Science Park',
    'location.hsinchu.addr': 'No. 18, Jieshou Rd., East Dist., Hsinchu City',
    'location.hsinchu.desc': 'Tailored for tech engineers and corporate elites! Open 24/7 with classic American iron-style strength brands, completed by a protein shake bar and relaxation massage area to balance work and fitness.',
    'location.kaohsiung.name': 'Kaohsiung Sanduo',
    'location.kaohsiung.addr': 'No. 213, Sanduo 3rd Rd., Qianzhen Dist., Kaohsiung City',
    'location.kaohsiung.desc': 'The ultimate fitness landmark in Southern Taiwan! Situated in Sanduo Shopping District with high-ceiling two-story training spaces, multi-functional CrossFit cages, indoor running tracks, and cold plunge therapy.',
    'location.tag.strength': 'Strength',
    'location.tag.grass': 'Turf',
    'location.tag.inbody': 'InBody',
    'location.tag.yoga': 'Yoga',
    'location.tag.pilates': 'Pilates',
    'location.tag.coffee': 'Coffee Bar',
    'location.tag.24h': '24H',
    'location.tag.cycling': 'Cycling',
    'location.tag.outdoor': 'Outdoor',
    'location.hours.24': '24/7 Open',
    'locations.visit_booking': 'Free Visit Booking',
    'locations.redirect_note': 'Redirecting in 3 seconds...',
    'locations.detail_meta_title': 'NEO-GYM Location Details',
    'contact.info.address_val': 'B1, No. 10, Ln. 347, Zhongzheng Rd., Xinzhuang Dist., New Taipei City',
    'contact.info.hours_val': '06:00 - 24:00 (Daily)',
    'dashboard.explore': 'Explore Member Features',
    'dashboard.premium_member': 'Premium Member',
    'dashboard.weekly_target': 'Weekly Target',
    'dashboard.consistency': 'Consistency',
    'dashboard.days': 'Days',
    'dashboard.new_record': 'New Record!',
    'dashboard.kcal_burned': '3,500 kcal burned this week',
    'tools.utilities': 'Fitness Utilities',
    'tools.bmi_result': 'Your Result',
    'tools.height_placeholder': 'Ex: 175',
    'tools.weight_placeholder': 'Ex: 70',
    'tools.round_prefix': 'Round',
    'tools.round_suffix': 'of',
    'tools.cups_suffix': 'Cups',
    'tools.progress': 'Progress',
    'schedule.group_classes': 'Group Classes Details',
    'schedule.classes_count': 'Classes',
    'membership.pricing_label': 'Pricing Plans',
    'coaching.program_detail': 'Program Details',
    'coaching.features_title': 'Highlights',
    'coaching.info_title': 'Information',
    'coaching.selector_subtitle': 'Click on a coach to see details and book a session',
    'coaching.match_note': 'Select a category to find your perfect coach match.',
    'coaching.match_cta': 'Find My Coach',
    'coaching.category_strength_desc': 'Perfect for those looking to boost squats and deadlifts for ultimate strength.',
    'coaching.category_sculpt_desc': 'Focused on muscle definition, fat loss, and perfect body proportions.',
    'coaching.category_health_desc': 'Gentle yet effective training to rebuild core and basic fitness.',
    'coaching.category_special_desc': 'Optimized for sports like baseball, golf, or marathons to boost power and endurance.',
    'coaching.why_desc': 'Personal trainers are your health management experts. Precise prescriptions shorten your path to success safely.',
    'coaching.science_desc': 'From FMS assessments to InBody analysis, our programs are science-based to quantify your progress.',
    'coaching.nutrition_desc': 'Training is 30%, nutrition is 70%. We help you build habits that last from the gym to the table.',
    'course.weight.title': 'Weight Training',
    'course.weight.desc': 'From basics to advanced powerlifting. Precise load management for muscle gain and metabolic boost.',
    'course.weight.feat1': 'Movement Assessment',
    'course.weight.feat2': 'Progressive Overload',
    'course.weight.feat3': 'Form Monitoring',
    'course.weight.feat4': 'Power Periodization',
    'course.weight.target': 'Muscle Gain, Strength',
    'course.relax.title': 'Muscle Recovery',
    'course.relax.desc': 'Using tools and manual stretching for deep release. Improve flexibility and prevent injuries.',
    'course.relax.feat1': 'Fascial Release',
    'course.relax.feat2': 'Mobility Optimization',
    'course.relax.feat3': 'Neuromuscular Prep',
    'course.relax.feat4': 'Restorative Stretch',
    'course.relax.target': 'Recovery, Prevention',
    'course.boxing.title': 'Boxing Skills',
    'course.boxing.desc': 'High-intensity interval training. Learn punches, slips, and footwork while boosting cardio.',
    'course.boxing.feat1': 'Basic Punching',
    'course.boxing.feat2': 'Pad Work',
    'course.boxing.feat3': 'Rotational Power',
    'course.boxing.feat4': 'Cardio Conditioning',
    'course.boxing.target': 'Agility, Cardio, Stress',
    'course.vipr.title': 'ViPR Functional',
    'course.vipr.desc': 'Full-body loaded movement training using ViPR. Bridges the gap between strength and movement.',
    'course.vipr.feat1': 'Multi-planar Movement',
    'course.vipr.feat2': 'Integrated Strength',
    'course.vipr.feat3': 'Stability Plus',
    'course.vipr.feat4': 'Functional Patterns',
    'course.vipr.target': 'Coordination, Function',
    'course.kettle.title': 'Kettlebell Blast',
    'course.kettle.desc': 'Focus on explosive power and endurance. From swings to snatches for an athlete physique.',
    'course.kettle.feat1': 'Pendulum Control',
    'course.kettle.feat2': 'Hip Power Dev',
    'course.kettle.feat3': 'Unilateral Stability',
    'course.kettle.feat4': 'Efficient Fat Burn',
    'course.kettle.target': 'Explosive Power',
    'course.suspension.title': 'Suspension Flow',
    'course.suspension.desc': 'Bodyweight training on unstable surfaces. Every second challenges your core and coordination.',
    'course.suspension.feat1': 'Total Core Engagement',
    'course.suspension.feat2': 'Unstable Surfaces',
    'course.suspension.feat3': 'Adjustable Intensity',
    'course.suspension.feat4': 'Full-body Synergies',
    'course.suspension.target': 'Core, Sculpting',
    'course.functional.title': 'Multi-Functional',
    'course.functional.desc': 'Battle ropes, slam balls, and sleds. Versatile training for overall athleticism.',
    'course.functional.feat1': 'Diverse Equipment',
    'course.functional.feat2': 'Energy System Work',
    'course.functional.feat3': 'Agility Challenges',
    'course.functional.feat4': 'PR Tracking',
    'course.functional.target': 'Overall Performance',
    'coach.marcus.spec': 'SBD Specialist, Power',
    'coach.jessica.spec': 'Female Sculpting, Fat Loss',
    'coach.david.spec': 'Powerlifting, Conditioning',
    'coach.sarah.spec': 'Postpartum & Senior Fitness',
    'coach.kevin.spec': 'Pro Athlete, Baseball',
    'coach.elena.spec': 'Pilates Integration',
    'coach.alex.spec': 'Bodybuilding, Max Strength',
    'coach.mina.spec': 'Figure Symmetry, Posture',
    'coach.leo.spec': 'Triathlon, Endurance',
    'coach.sophia.spec': 'Elderly Care, Rehab',
    'coach.james.spec': 'Tactical Fitness, Combat',
    'coach.crofts.spec': 'Adventure Specialist',
    'games.hurdles.name': 'Obstacle Race',
    'games.hurdles.instructions': 'Tap or use arrow keys to guide the athlete to the finish.',
    'games.hurdles.static': 'Static Obstacle',
    'games.hurdles.moving': 'Moving Trap',
    'games.hurdles.enter': 'Enter Stadium',
    'games.hurdles.select_level': 'Select Difficulty',
    'games.hurdles.level_easy': 'Easy: Walk',
    'games.hurdles.level_medium': 'Medium: Dash',
    'games.hurdles.level_hard': 'Elite: Sprint',
    'games.hurdles.desc_easy': 'Few obstacles, slow pace',
    'games.hurdles.desc_medium': 'Denser path with moving traps',
    'games.hurdles.desc_hard': 'Extreme challenge for reaction speed',
    'games.hurdles.retry': 'Retry',
    'games.hurdles.goal': 'Goal Reached!',
    'games.hurdles.points': 'Points',
    'games.hurdles.again': 'Play Again',
    'games.hurdles.controls': 'Use WASD / Arrows or Tap to move',
    'games.sprint.stadium': 'Athlete Stadium',
    'games.sprint.champion': 'YOU ARE THE CHAMP!',
    'games.sprint.keep_running': 'Keep Pushing!',
    'games.sprint.go': 'GO!',
    'games.sprint.finish': 'FINISH!',
    'games.sprint.crashed': 'CRASHED!',
    'membership.inbody_title': 'InBody Body Composition',
    'membership.inbody.details_title': 'Body Composition Analysis Details',
    'membership.inbody_price': '5 / test',
    'membership.inbody_desc': 'Advanced InBody 270 precision analysis for body fat, muscle mass, and metabolism.',
    'membership.inbody.fat': 'Fat %',
    'membership.inbody.fat_val': 'Precision',
    'membership.inbody.muscle': 'Muscle',
    'membership.inbody.muscle_val': 'Detailed',
    'membership.inbody.metabolism': 'Metabolism',
    'membership.inbody.metabolism_val': 'BMR Index',
    'membership.inbody.balance': 'Balance',
    'membership.inbody.balance_val': 'Segmental',
    'membership.inbody.visceral': 'Visceral Fat',
    'membership.inbody.visceral_val': 'Health Index',
    'membership.inbody.water': 'Body Water',
    'membership.inbody.water_val': 'Hydration',
    'membership.inbody.bmc': 'Bone Mineral',
    'membership.inbody.bmc_val': 'Density',
    'membership.inbody.bmi': 'BMI Index',
    'membership.inbody.bmi_val': 'Body Mass',
    'membership.inbody.fat_desc': 'Fat percentage reflects the ratio of fat to body weight. Healthy levels protect organs and balance hormones.',
    'membership.inbody.muscle_desc': 'Skeletal muscle mass is key for metabolism and power. Increasing it raises your BMR.',
    'membership.inbody.metabolism_desc': 'BMR is the energy needed for vital functions. Higher BMR prevents fat accumulation.',
    'membership.inbody.balance_desc': 'Analyzes left/right muscle distribution to identify imbalances or structural compensations.',
    'membership.inbody.visceral_desc': 'High visceral fat correlates with cardiovascular risks. Crucial for long-term health tracking.',
    'membership.inbody.water_desc': 'Ensures your body is properly hydrated, which is vital for muscle repair and nutrient transport.',
    'membership.inbody.bmc_desc': 'Measures mineral content in your bones, indicating bone strength and future osteoporosis risks.',
    'membership.inbody.bmi_desc': 'A standard global indicator for body mass, though it doesn\'t differentiate muscle from fat.',
    'dashboard.tag': 'SMART ECOSYSTEM',
    'dashboard.title': 'TRACK YOUR EVOLUTION',
    'dashboard.desc': 'Our advanced tracking system provides real-time insights into your performance. Sync your training data, monitor your progress, and beat your personal records every week.',
    'dashboard.stat1.title': 'REAL-TIME STATS',
    'dashboard.stat1.desc': 'View your heart rate and calorie burn in real-time.',
    'dashboard.stat2.title': 'GOAL ORIENTED',
    'dashboard.stat2.desc': 'Set weekly targets and get notified as you get closer.',
    'story.result.weightloss': 'Weight Loss',
    'story.result.fitness': 'Improved Fitness',
    'story.result.painfree': 'Pain-Free Life',
    'story.result.recomp': 'Body Recomposition',
    'story.stat.months': 'Months',
    'story.stat.year': 'Year',
    'story.stat.beginner': 'Beginner',
    'story.stat.runner': 'Runner',
    'story.stat.sedentary': 'Sedentary',
    'story.stat.active': 'Active',
    'dashboard.stat3.title': 'ACHIEVEMENT SYSTEM',
    'dashboard.stat3.desc': 'Earn badges and rank up in our local leaderboard.',
    'dashboard.stat4.title': 'STREAK TRACKING',
    'dashboard.stat4.desc': 'Keep the momentum going with consistency bonuses.',
    'dashboard.chart.title': 'Calorie Trend',
    'dashboard.chart.subtitle': 'CALORIE CONSUMPTION TREND',
    'dashboard.chart.total': '7-DAY TOTAL KCAL',
    'tools.title': 'Fitness Tools',
    'tools.bmi_title': 'BMI Calculator',
    'tools.bmi_subtitle': 'Body Assessment',
    'tools.hiit_title': 'HIIT Timer',
    'tools.hiit_subtitle': 'Interval Training',
    'tools.water_title': 'Daily Water',
    'tools.water_subtitle': 'Hydration Tracking',
    'tools.height': 'Height (cm)',
    'tools.weight': 'Weight (kg)',
    'tools.calculate_bmi': 'Calculate BMI',
    'tools.bmi_underweight': 'Underweight',
    'tools.bmi_normal': 'Normal',
    'tools.bmi_overweight': 'Overweight',
    'tools.bmi_obese1': 'Obese I',
    'tools.bmi_obese2': 'Obese II',
    'tools.bmi_obese3': 'Obese III',
    'tools.work': 'Work (sec)',
    'tools.rest': 'Rest (sec)',
    'tools.rounds': 'Rounds',
    'tools.working': '🔥🔥 Working',
    'tools.resting': '🧊🧊 Resting',
    'tools.water_goal_desc': 'Suggested daily intake 2000ml+ (approx. 8 cups)',
    'tools.water_achieved': 'Goal Reached! Well Hydrated 💧',
    'tools.water.calculate': 'Calculate My Goal',
    'tools.water.formula_desc': 'Your goal is calculated as weight (kg) × 35 ml',
    'tools.water.calc_result_prefix': 'Your daily water goal is ',
    'tools.water.calc_result_suffix': 'ml (approx. {cups} cups of 250ml)',
    'tools.water.reset_calc': 'Reset Calculator',
    'tools.workout_title': 'AI Workout',
    'tools.workout_subtitle': 'Smart Generator',
    'tools.workout_generator_title': 'AI Workout Generator',
    'tools.workout_generator_desc': 'Instant personalized training content based on your goals and available equipment.',
    'tools.workout_label_goal': 'Training Goal',
    'tools.workout_label_level': 'Your Level',
    'tools.workout_label_equipment': 'Equipment',
    'tools.workout_btn_generate': 'Generate Workout',
    'tools.workout_btn_generating': 'Generating...',
    'tools.workout_coach_note': 'AI Coach Recommendation',
    'tools.workout_placeholder_title': 'Awaiting Parameters',
    'tools.workout_placeholder_desc': 'Select your goals and hit generate',
    'tools.workout.goal_muscle': 'Muscle Gain',
    'tools.workout.goal_fat': 'Fat Loss',
    'tools.workout.goal_strength': 'Strength',
    'tools.workout.goal_health': 'Health',
    'tools.workout.level_beginner': 'Beginner',
    'tools.workout.level_intermediate': 'Intermediate',
    'tools.workout.level_advanced': 'Advanced',
    'tools.workout.eq_dumbbell': 'Dumbbell',
    'tools.workout.eq_barbell': 'Barbell',
    'tools.workout.eq_cable': 'Cable Machine',
    'tools.workout.eq_kettlebell': 'Kettlebell',
    'tools.workout.eq_pullup': 'Pull-up Bar',
    'tools.workout.eq_bodyweight': 'Bodyweight',
    'games.sprint.instructions': 'Alternate A/D to sprint! Compete with 5 elite AIs. Supports 100m & 200m distances.',
    'games.sprint.enter': 'Prepare to Race',
    'games.sprint.classic': 'Classic Neon',
    'games.sprint.volcano': 'Volcano Wastes',
    'games.sprint.jungle': 'Cyber Jungle',
    'games.sprint.deepsea': 'Deep Sea Pressure',
    'games.sprint.back_main': 'Back to Menu',
    'games.sprint.sprint_100': 'Extreme Sprint',
    'games.sprint.sprint_200': 'Endurance Burst',
    'games.sprint.reselect_env': 'Reselect Environment',
    'games.sprint.again': 'Race Again',
    'games.sprint.runner': 'AI Runner',
    'success.title': 'Success Stories',
    'success.details_title': 'Transformation Details',
    'success.cta': 'I want to book an experience plan too',
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Ready to start your path of strength? Leave your contact info and our consultants will reach out within 24 hours.',
    'contact.form.name': 'Full Name',
    'contact.form.phone': 'Phone Number',
    'contact.form.email': 'Email Address',
    'contact.form.subject': 'Inquiry Subject',
    'contact.form.message': 'Message Content',
    'contact.form.submit': 'Send Inquiry Message',
    'contact.form.success': 'Message Sent Successfully',
    'contact.info.address': 'Company Address',
    'contact.info.phone': 'Inquiry Hotline',
    'contact.info.email': 'Email',
    'contact.info.hours': 'Service Hours',
    'courses.title': 'Pro Training Courses',
    'courses.subtitle': 'Diverse high-intensity courses based on your goals, from core sculpting to power enhancement, releasing full potential.',
    'courses.target_group': 'Target Group',
    'courses.goals_title': 'Course Goals',
    'courses.details_title': 'Course Details',
    'courses.duration_label': 'Estimated Duration:',
    'courses.book_now': 'Book Experience Now',
    'schedule.morning_flow': 'Morning Flow Yoga',
    'schedule.spinning': 'Power Spinning',
    'schedule.mma': 'Mixed Martial Arts (MMA)',
    'schedule.trx': 'TRX Total Body',
    'schedule.foam_roll': 'Foam Rolling Recovery',
    'schedule.bootcamp': 'Morning Bootcamp',
    'schedule.core_base': 'Core Foundation',
    'schedule.noon_strength': 'Noon Strength Build',
    'schedule.yin_yoga': 'Mindful Yin Yoga',
    'schedule.zumba': 'Zumba Party',
    'schedule.reformer': 'Reformer Pilates',
    'schedule.hiit_burn': 'HIIT Fat Burning',
    'schedule.boxing_base': 'Modern Boxing Basics',
    'schedule.functional_challenge': 'Functional Challenge',
    'schedule.sound_healing': 'Sound Healing Yoga',
    'schedule.barbell_strength': 'Barbell Strength',
    'schedule.tabata_flash': 'Tabata Express',
    'schedule.muay_thai': 'Muay Thai Basics',
    'schedule.air_yoga': 'Aerial Yoga Sculpt',
    'schedule.leg_sculpt': 'Leg Stretch & Sculpt',
    'schedule.dawn_flow': 'Dawn Energy Yoga',
    'schedule.kettlebell': 'Kettlebell Endurance',
    'schedule.krav_maga': 'Krav Maga Defense',
    'schedule.glow_cycle': 'Night Glow Cycle',
    'schedule.aroma_yoga': 'Aromatherapy Yoga',
    'schedule.warrior_camp': 'Weekend Warrior Camp',
    'schedule.balance_core': 'Dynamic Core & Balance',
    'schedule.air_stretch': 'Anti-Gravity Stretch',
    'schedule.bjj': 'Brazilian Jiu-Jitsu Basics',
    'schedule.twilight_meditation': 'Twilight Meditation',
    'schedule.morning_dance': 'Morning Dance Challenge',
    'schedule.body_recovery': 'Full Body Recovery',
    'schedule.kpop_dance': 'K-Pop Dance Party',
    'schedule.rucking': 'Rucking Exploration',
    'schedule.muscle_balance': 'Muscle Balance Assessment',
    'schedule.level_all': 'All Levels',
    'schedule.level_beginner': 'Beginner',
    'schedule.level_intermediate': 'Intermediate',
    'schedule.level_advanced': 'Advanced',
    'schedule.tag_relaxation': 'Relaxation',
    'schedule.tag_cardio': 'Cardio',
    'schedule.tag_combat': 'Combat',
    'schedule.tag_strength': 'Strength',
    'schedule.tag_recovery': 'Recovery',
    'schedule.tag_intensity': 'High Intensity',
    'schedule.tag_core': 'Core',
    'schedule.tag_dance': 'Dance',
    'schedule.tag_wellness': 'Wellness',
    'schedule.tag_fitness': 'Fitness',
    'schedule.tag_flexibility': 'Flexibility',
    'schedule.tag_flow': 'Flow',
    'schedule.tag_defense': 'Defense',
    'schedule.tag_challenge': 'Challenge',
    'schedule.tag_air_yoga': 'Air Yoga',
    'schedule.tag_peace': 'Peace',
    'schedule.tag_fun': 'Fun',
    'schedule.tag_outdoor': 'Outdoor',
    'schedule.tag_consult': 'Consult',
    'schedule.cat_hiit': 'HIIT',
    'schedule.cat_dance': 'Dance Party',
    'schedule.cat_wellness': 'Mind & Body',
    'schedule.cat_pick': 'Top Pick',
    'schedule.morning_flow.desc': 'Gently wake up your body with breath and flow, bringing peace and vitality to your day.',
    'schedule.spinning.desc': 'Ride with the rhythm and burn calories in this high-intensity cardiovascular workout.',
    'schedule.mma.desc': 'Combines boxing, Muay Thai, and wrestling to improve coordination and explosive power.',
    'schedule.trx.desc': 'Total body resistance training using suspension straps to challenge strength and stability.',
    'schedule.foam_roll.desc': 'Deep release for muscles after exercise, improving flexibility and preventing injuries.',
    'schedule.bootcamp.desc': 'High-intensity morning workout for early birds, combining intervals and bodyweight.',
    'schedule.core_base.desc': 'Focus on deep core group stability to improve posture and functional movement.',
    'schedule.noon_strength.desc': 'Targeted training for core and major muscle groups during your lunch break.',
    'schedule.yin_yoga.desc': 'Long holds and mindful stillness targeting deep connective tissues and joints.',
    'schedule.zumba.desc': 'High-energy Latin dance rhythms for a fun and effective full-body fat burn.',
    'schedule.reformer.desc': 'Precision core training using professional machinery to sculpt and lengthen.',
    'schedule.hiit_burn.desc': 'Extreme body conditioning with short periods of intense anaerobic exercise.',
    'schedule.boxing_base.desc': 'Learn proper punching techniques and footwork in a stress-relieving workout.',
    'schedule.functional_challenge.desc': 'Simulate daily movements for a comprehensive workout enhancing speed and agility.',
    'schedule.sound_healing.desc': 'Tibetan bowl sound therapy with gentle stretching for deep mental purification.',
    'schedule.barbell_strength.desc': 'Scientific weight training to build solid muscle mass and boost metabolism.',
    'schedule.tabata_flash.desc': '20s work / 10s rest protocol for maximum caloric expenditure in short bursts.',
    'schedule.muay_thai.desc': 'The art of eight limbs: punch, kick, elbow, and knee techniques for defense.',
    'schedule.air_yoga.desc': 'Suspended in hammocks, challenge core strength and body balance in zero-gravity.',
    'schedule.leg_sculpt.desc': 'Focused lower body stretching to reduce swelling and sculpt sleek leg lines.',
    'schedule.dawn_flow.desc': 'Dance with the first light of dawn, stretching the body into a creative state.',
    'schedule.kettlebell.desc': 'Integrated full-body power training enhancing stability and explosive strength.',
    'schedule.krav_maga.desc': 'Practical self-defense techniques in a dynamic, scenario-based environment.',
    'schedule.glow_cycle.desc': 'Low-frequency beats and neon lights for an immersive fat-burning experience.',
    'schedule.aroma_yoga.desc': 'Plant essential oil healing for absolute relaxation to kick off your weekend.',
    'schedule.warrior_camp.desc': 'A hardcore endurance marathon testing explosive power and mental grit.',
    'schedule.balance_core.desc': 'Multi-planar movement design challenging neurological control over the core.',
    'schedule.air_stretch.desc': 'Low-altitude suspension focusing on fine-tuning skeletal Alignment and stretch.',
    'schedule.bjj.desc': 'The gentle art. Learn ground fighting and grappling for sensory and strategic gain.',
    'schedule.twilight_meditation.desc': 'Sunset collective meditation sync with nature for deep physical harmony.',
    'schedule.morning_dance.desc': 'Modern dance and pop rhythms for a dynamic start to a relaxed Sunday.',
    'schedule.body_recovery.desc': 'Systemic functional repair for fatigue accumulated throughout the training week.',
    'schedule.kpop_dance.desc': 'Learn hot K-Pop choreography highlights, no prior dance experience needed.',
    'schedule.rucking.desc': 'Simulated weighted marching to reinforce core endurance and physiological strength.',
    'schedule.muscle_balance.desc': 'Group posture screening and correction to identify and optimize body links.',
    'schedule.capacity': 'Spots Left',
    'games.sprint.select_env': 'Select Environment',
    'games.sprint.select_dist': 'Select Distance',
    'games.sprint.time': 'Time',
    'games.sprint.score': 'Power Score',
    'games.sprint.you': 'YOU',
    'landing.hero.subtitle': 'Professional Training Studio',
    'landing.courses.featured': 'Featured Courses',
    'landing.stories.title': 'Success Stories',
    'landing.stories.subtitle': 'Our members achieve incredible progress under the guidance of our professional coaches.',
    'landing.stories.details_title': 'Transformation Details',
    'landing.stories.before': 'Before',
    'landing.stories.after': 'After',
    'landing.stories.duration': 'Duration',
    'landing.stories.cta': 'Start My Transformation',
    'landing.contact.featured': 'Contact Us',
    'landing.newsletter.title': 'Join the Movement',
    'landing.newsletter.subtitle': 'Subscribe to our newsletter for exclusive training tips, nutrition guides, and community event updates.',
    'landing.newsletter.placeholder': 'YOUR.EMAIL@WORK.COM',
    'landing.newsletter.subscribe': 'Subscribe',
    'landing.newsletter.spam_note': 'No Spam. Just Pure Value. Unsubscribe at any time.',
    'course.sculpt.title': 'Ultimate Body Sculpt',
    'course.sculpt.category': 'Strength',
    'course.sculpt.price': 'NT$ 1,200 / Session',
    'course.sculpt.target': 'For those seeking muscle definition, building mass, or preparing for competitions.',
    'course.sculpt.goal1': 'Muscle Hypertrophy',
    'course.sculpt.goal2': 'Precision Sculpting',
    'course.sculpt.goal3': 'Boost Metabolism',
    'course.sculpt.content': 'Using scientific progressive overload to stimulate muscle groups deeply. Core strength assessment and form correction included.',
    'course.sculpt.duration': '60 min',
    'course.burn.title': 'High-Efficiency Burn',
    'course.burn.category': 'Cardio & Endurance',
    'course.burn.price': 'NT$ 1,000 / Session',
    'course.burn.target': 'For those looking to burn maximum calories and improve cardiovascular health.',
    'course.burn.goal1': 'Extreme Fat Burn',
    'course.burn.goal2': 'Improve Endurance',
    'course.burn.goal3': 'Boost Performance',
    'course.burn.content': 'Combines HIIT with functional movements. Keep burning calories after your workout with the afterburn effect.',
    'course.burn.duration': '50 min',
    'course.core.title': 'Core Stability Plus',
    'course.core.category': 'Functional',
    'course.core.price': 'NT$ 1,100 / Session',
    'course.core.target': 'For sedentary workers, those with poor posture, or athletes needing stability.',
    'course.core.goal1': 'Injury Prevention',
    'course.core.goal2': 'Postural Correction',
    'course.core.goal3': 'Deep Core Strength',
    'course.core.content': 'Focus on spinal stability and multi-planar control. Uses Pilates and suspension tools to build a strong foundation.',
    'course.core.duration': '50 min',
    'story.lin.name': 'Mr. Lin',
    'story.lin.story': 'Lost 15kg and gained 5kg of muscle in 6 months at NEO-GYM.',
    'story.lin.details': 'Mr. Lin neglected his health due to a busy schedule. With coach guidance, he started with twice-weekly strength training and strict diet control, resulting in improved health markers and stamina.',
    'story.chang.name': 'Ms. Chang',
    'story.chang.story': 'Lost 3kg and completed her first half-marathon in 12 months at NEO-GYM.',
    'story.chang.details': 'Ms. Chang originally lacked confidence and was intimidated by gym environments. Guided by her coach, she developed core and cardio endurance over 12 months, gaining the strength to finish her first half-marathon.',
    'story.wang.name': 'Mr. Wang',
    'story.wang.story': 'Lost 6kg and completely eliminated chronic back pain in 8 months at NEO-GYM.',
    'story.wang.details': 'Mr. Wang suffered from chronic lower back pain linked to his engineering job. Through Redcord and functional training, he strengthened his deep core over 8 months, leading to a pain-free life and better mobility.',
    'story.lee.name': 'Ms. Lee',
    'story.lee.story': 'Reduced body fat by 8% and reclaimed post-pregnancy confidence in 10 months at NEO-GYM.',
    'story.lee.details': 'Ms. Lee struggled with post-pregnancy physical changes and low self-esteem. Through personal training and nutrition consulting, she mastered metabolism and reached a lower body fat percentage than ever before.',
  },
  'vi': {
    'brand': 'NEO-GYM Phòng tập thể hình',
    'nav.home': 'Trang chủ',
    'nav.about': 'Giới thiệu',
    'nav.features': 'Tính năng',
    'nav.courses': 'Khóa học',
    'nav.coaching': 'HLV Cá nhân',
    'nav.schedule': 'Lịch trình',
    'nav.locations': 'Chi nhánh',
    'nav.membership': 'Hội viên',
    'nav.contact': 'Liên hệ',
    'nav.login': 'Đăng nhập',
    'hero.title': 'Vượt qua giới hạn',
    'hero.subtitle': 'Vượt qua chính mình',
    'hero.description': 'Thiết bị hàng đầu, không gian đẳng cấp, đội ngũ huấn luyện viên chuyên nghiệp.',
    'hero.start': 'Bắt đầu theo dõi',
    'hero.explore': 'Dùng thử miễn phí',
    'hero.contact': 'Liên hệ tư vấn',
    'features.title': 'Cơ sở vật chất hàng đầu',
    'features.tag': 'Cơ sở vật chất',
    'features.cardio.title': 'Khu Cardio cao cấp',
    'features.cardio.desc': 'Máy chạy bộ và xe đạp hiện đại với đồng bộ dữ liệu.',
    'features.strength.title': 'Khu kháng lực nặng',
    'features.strength.desc': 'Giá đỡ squat và thiết bị nâng tạ chuyên nghiệp.',
    'features.functional.title': 'Huấn luyện chức năng',
    'features.functional.desc': 'Sân cỏ, xe kéo và dây thừng chiến đấu.',
    'schedule.title': 'Lịch học nhóm',
    'schedule.tag': 'Lớp học nhóm',
    'schedule.mon': 'Thứ 2',
    'schedule.tue': 'Thứ 3',
    'schedule.wed': 'Thứ 4',
    'schedule.thu': 'Thứ 5',
    'schedule.fri': 'Thứ 6',
    'schedule.sat': 'Thứ 7',
    'schedule.sun': 'Chủ nhật',
    'schedule.detail': 'Xem chi tiết',
    'schedule.booking': 'Đặt lớp ngay',
    'schedule.success': 'Đặt lớp thành công!',
    'locations.title': 'Hệ thống chi nhánh',
    'locations.tag': 'Chi nhánh của chúng tôi',
    'locations.search': 'Tìm chi nhánh...',
    'locations.visit': 'Đặt lịch tham quan',
    'locations.full_schedule': 'Lịch học chi tiết',
    'coaching.title': 'Huấn luyện viên cá nhân',
    'coaching.tag': 'Huấn luyện cá nhân',
    'coaching.more': 'Tìm hiểu thêm',
    'coaching.find': 'Tìm huấn luyện viên',
    'coaching.reserve': 'Đặt lịch tư vấn',
    'footer.rights': '© 2026 NEO-GYM. Bảo lưu mọi quyền.',
    'common.name': 'Họ tên',
    'common.phone': 'Số điện thoại',
    'common.email': 'Email',
    'common.submit': 'Xác nhận gửi',
    'schedule.booking_title': 'Thông tin đặt chỗ',
    'schedule.booking_success': 'Đặt lớp thành công!',
    'schedule.booking_received': 'Chúng tôi đã nhận được yêu cầu đặt chỗ của bạn.',
    'schedule.instructor': 'Huấn luyện viên',
    'schedule.level': 'Cấp độ đề xuất',
    'schedule.intro': 'Giới thiệu khóa học',
    'locations.booking_title': 'Đặt lịch tham quan miễn phí',
    'locations.booking_success': 'Đặt lịch tham quan thành công!',
    'locations.booking_received': 'Chuyên viên sẽ liên hệ với bạn trong vòng 24 giờ.',
    'locations.details_btn': 'Xem chi tiết chi nhánh',
    'locations.facilities': 'Tiện nghi',
    'locations.contact_info': 'Thông tin liên hệ',
    'contact.form.subject_default': 'Nhận gói trải nghiệm 7 ngày miễn phí',
    'contact.form.error': 'Đã xảy ra lỗi, vui lòng thử lại sau.',
    'contact.form.success_desc': 'Cảm ơn bạn đã quan tâm, chuyên viên sẽ liên hệ với bạn sớm nhất.',
    'contact.form.retry': 'Gửi một tin nhắn khác',
    'social.title': 'Mạng xã hội',
    'social.owner': 'Chủ sở hữu',
    'social.coach': 'Huấn luyện viên',
    'social.secretary1': 'Thư ký 1',
    'social.secretary2': 'Thư ký 2',
    'courses.reserve_btn': 'Đặt chỗ ngay',
    'success.before': 'Trước',
    'success.after': 'Sau',
    'success.duration': 'Thời gian',
    'coaching.philosophy_title': 'Về HLV cá nhân tại NEO-GYM',
    'coaching.why_title': 'Tại sao chọn HLV cá nhân?',
    'coaching.science_title': 'Quy trình đào tạo khoa học',
    'coaching.nutrition_title': 'Hướng dẫn dinh dưỡng toàn diện',
    'coaching.match_title': 'Tìm huấn luyện viên phù hợp',
    'coaching.category_strength': 'Tăng cường sức mạnh',
    'coaching.category_sculpt': 'Điêu khắc hình thể',
    'coaching.category_health': 'Sau sinh/Sức khỏe',
    'coaching.category_special': 'Tăng cường thể thao chuyên biệt',
    'coaching.select_title': 'Chọn huấn luyện viên của bạn',
    'coaching.back': '← Quay lại danh mục',
    'coaching.note': 'Ghi chú / Yêu cầu (Tùy chọn)',
    'ai.title': 'Huấn luyện viên AI',
    'ai.empty': 'Có bất kỳ câu hỏi nào về thể dục? Hãy hỏi tôi! Các cuộc hội thoại được lưu tự động.',
    'ai.placeholder': 'Hỏi về kế hoạch hoặc kỹ thuật...',
    'ai.clear_confirm': 'Bạn có chắc chắn muốn xóa tất cả lịch sử trò chuyện không?',
    'ai.clear_tooltip': 'Xóa lịch sử trò chuyện',
    'ai.error_response': 'Tôi không thể trả lời câu hỏi này lúc này, vui lòng thử lại sau.',
    'ai.network_error': 'Xin lỗi, đã xảy ra lỗi. Vui lòng kiểm tra kết nối của bạn hoặc thử lại sau.',
    'tools.title': 'Công cụ thể dục',
    'tools.bmi_title': 'Máy tính BMI',
    'tools.bmi_subtitle': 'Đánh giá cơ thể',
    'tools.hiit_title': 'Đồng hồ HIIT',
    'tools.hiit_subtitle': 'Tập luyện ngắt quãng',
    'tools.water_title': 'Nước hàng ngày',
    'tools.water_subtitle': 'Theo dõi hydrat hóa',
    'tools.height': 'Chiều cao (cm)',
    'tools.weight': 'Cân nặng (kg)',
    'tools.calculate_bmi': 'Tính chỉ số BMI',
    'tools.bmi_underweight': 'Thiếu cân',
    'tools.bmi_normal': 'Bình thường',
    'tools.bmi_overweight': 'Thừa cân',
    'tools.bmi_obese1': 'Béo phì độ 1',
    'tools.bmi_obese2': 'Béo phì độ 2',
    'tools.bmi_obese3': 'Béo phì độ 3',
    'tools.work': 'Làm việc (giây)',
    'tools.rest': 'Nghỉ ngơi (giây)',
    'tools.rounds': 'Số vòng',
    'tools.working': '🔥🔥 Đang tập',
    'tools.resting': '🧊🧊 Đang nghỉ',
    'tools.water_goal_desc': 'Khuyên dùng hàng ngày trên 2000ml (khoảng 8 ly)',
    'tools.water_achieved': 'Đạt được mục tiêu! Đã cung cấp đủ nước 💧',
    'games.hurdles.instructions': 'Sử dụng phím mũi tên ↑ ↓ ← → để né tránh vật cản!',
    'games.hurdles.static': 'Tĩnh',
    'games.hurdles.moving': 'Di chuyển lên/xuống',
    'games.hurdles.enter': 'Vào cấp độ',
    'games.hurdles.level_easy': 'Dễ',
    'games.hurdles.level_medium': 'Vừa',
    'games.hurdles.level_hard': 'Khó',
    'games.hurdles.desc_easy': 'Ít vật cản / Tốc độ chậm',
    'games.hurdles.desc_medium': 'Mật độ trung bình / Tốc độ chuẩn',
    'games.hurdles.desc_hard': 'Mật độ cao / Di chuyển nhanh',
    'games.hurdles.retry': 'Thử lại',
    'games.hurdles.again': 'Chạy lại',
    'games.sprint.instructions': 'Nhấn luân phiên A/D để chạy nước rút! Thi đấu với 5 AI ưu tú. Hỗ trợ 100m & 200m.',
    'games.sprint.enter': 'Chuẩn bị thi đấu',
    'games.sprint.classic': 'Neon cổ điển',
    'games.sprint.volcano': 'Hoang mạc núi lửa',
    'games.sprint.jungle': 'Rừng rậm không gian mạng',
    'games.sprint.deepsea': 'Áp suất biển sâu',
    'games.sprint.back_main': 'Quay lại menu',
    'games.sprint.sprint_100': 'Chạy nước rút cực hạn',
    'games.sprint.sprint_200': 'Bùng nổ sức bền',
    'games.sprint.reselect_env': 'Chọn lại môi trường',
    'games.sprint.again': 'Thi đấu lại',
    'games.sprint.runner': 'Người chạy AI',
    'success.title': 'Câu chuyện thành công',
    'success.details_title': 'Chi tiết chuyển đổi',
    'success.cta': 'Tôi cũng muốn đặt lịch trải nghiệm',
    'contact.title': 'Liên hệ với chúng tôi',
    'contact.subtitle': 'Sẵn sàng bắt đầu con đường sức mạnh của bạn? Để lại thông tin và cố vấn của chúng tôi sẽ liên hệ trong vòng 24 giờ.',
    'contact.form.name': 'Họ và tên',
    'contact.form.phone': 'Số điện thoại',
    'contact.form.email': 'Địa chỉ Email',
    'contact.form.subject': 'Chủ đề tư vấn',
    'contact.form.message': 'Nội dung tin nhắn',
    'contact.form.submit': 'Gửi tin nhắn tư vấn',
    'contact.form.success': 'Gửi tin nhắn thành công',
    'contact.info.address': 'Địa chỉ công ty',
    'contact.info.phone': 'Hotline tư vấn',
    'contact.info.email': 'Email',
    'contact.info.hours': 'Giờ phục vụ',
    'courses.title': 'Khóa học đào tạo chuyên nghiệp',
    'courses.subtitle': 'Các khóa học cường độ cao đa dạng dựa trên mục tiêu của bạn, từ điêu khắc cốt lõi đến tăng cường sức mạnh.',
    'courses.target_group': 'Nhóm mục tiêu',
    'courses.goals_title': 'Mục tiêu khóa học',
    'courses.details_title': 'Chi tiết khóa học',
    'courses.duration_label': 'Thời gian dự kiến:',
    'courses.book_now': 'Đặt lịch trải nghiệm ngay',
    'story.lin.name': 'Ông Lin',
    'story.lin.story': 'Giảm 15kg và tăng 5kg cơ bắp trong 6 tháng tại NEO-GYM.',
    'story.lin.details': 'Ông Lin từng bỏ bê sức khỏe do lịch trình bận rộn. Với sự hướng dẫn của huấn luyện viên, ông bắt đầu tập luyện sức mạnh hai lần mỗi tuần và kiểm soát chế độ ăn uống nghiêm ngặt.',
    'story.chang.name': 'Bà Chang',
    'story.chang.story': 'Giảm 3kg và hoàn thành cuộc chạy marathon đầu tiên trong 12 tháng tại NEO-GYM.',
    'story.chang.details': 'Bà Chang ban đầu thiếu tự tin và lo sợ môi trường phòng tập. Được sự hướng dẫn sát sao, bà đã phát triển sức bền trong 12 tháng và hoàn thành mục tiêu chạy bộ.',
    'story.wang.name': 'Ông Wang',
    'story.wang.story': 'Giảm 6kg và loại bỏ hoàn toàn chứng đau lưng mãn tính trong 8 tháng tại NEO-GYM.',
    'story.wang.details': 'Ông Wang bị đau lưng do đặc thù công việc kỹ sư. Qua 8 tháng tập luyện phục hồi chức năng, ông đã tăng cường sức mạnh cốt lõi và không còn đau đớn.',
    'story.lee.name': 'Bà Lee',
    'story.lee.story': 'Giảm 8% mỡ cơ thể và lấy lại sự tự tin sau khi sinh trong 10 tháng tại NEO-GYM.',
    'story.lee.details': 'Bà Lee từng gặp khó khăn về cân nặng sau sinh. Nhờ tư vấn dinh dưỡng và tập luyện cá nhân, bà đã làm chủ quá trình trao đổi chất và lấy lại vóc dáng.',
  },
  'id': {
    'brand': 'NEO-GYM Pusat Kebugaran',
    'nav.home': 'Beranda',
    'nav.about': 'Tentang',
    'nav.features': 'Fitur',
    'nav.courses': 'Kursus',
    'nav.coaching': 'Pelatih',
    'nav.schedule': 'Jadwal',
    'nav.locations': 'Lokasi',
    'nav.membership': 'Keanggotaan',
    'nav.contact': 'Kontak',
    'nav.login': 'Masuk',
    'hero.title': 'Lampaui Batas Anda',
    'hero.subtitle': 'LAMPAUI DIRIMU',
    'hero.description': 'Peralatan kelas atas, ruang terbaik, tim pelatih profesional, lahir untuk evolusi Anda.',
    'hero.start': 'Mulai Pelacakan',
    'hero.explore': 'Coba Gratis',
    'hero.contact': 'Hubungi Konselor',
    'features.title': 'Fasilitas Utama',
    'features.tag': 'Fasilitas Utama',
    'features.cardio.title': 'Kardiovaskular Lanjut',
    'features.cardio.desc': 'Treadmill dan sepeda kelas atas dengan sinkronisasi data.',
    'features.strength.title': 'Resistensi Berat',
    'features.strength.desc': 'Rak squat ganda dan peralatan angkat beban profesional.',
    'features.functional.title': 'Pelatihan Fungsional',
    'features.functional.desc': 'Rumput, kereta luncur, dan tali tempur.',
    'schedule.title': 'Jadwal Kelas',
    'schedule.tag': 'Kelas Grup',
    'schedule.mon': 'Sen',
    'schedule.tue': 'Sel',
    'schedule.wed': 'Rab',
    'schedule.thu': 'Kam',
    'schedule.fri': 'Jum',
    'schedule.sat': 'Sab',
    'schedule.sun': 'Min',
    'schedule.detail': 'Lihat Detail',
    'schedule.booking': 'Pesan Kelas Sekarang',
    'schedule.success': 'Pemesanan Berhasil!',
    'locations.title': 'Cabang Nasional',
    'locations.tag': 'Lokasi Kami',
    'locations.search': 'Cari cabang...',
    'locations.visit': 'Pesan Kunjungan Gratis',
    'locations.full_schedule': 'Jadwal Lengkap',
    'coaching.title': 'Pelatih Pribadi',
    'coaching.tag': 'Pelatihan Pribadi',
    'coaching.more': 'Pelajari Lebih Lanjut',
    'coaching.find': 'Cari Pelatih',
    'coaching.reserve': 'Reservasi Konsultasi',
    'footer.rights': '© 2026 NEO-GYM. Seluruh hak cipta dilindungi.',
    'common.name': 'Nama',
    'common.phone': 'Telepon',
    'common.email': 'Email',
    'common.submit': 'Kirim',
    'schedule.booking_title': 'Informasi Pemesanan',
    'schedule.booking_success': 'Kelas Berhasil Dipesan!',
    'schedule.booking_received': 'Kami telah menerima permintaan pemesanan Anda.',
    'schedule.instructor': 'Instruktur',
    'schedule.level': 'Tingkat',
    'schedule.intro': 'Pendahuluan',
    'locations.booking_title': 'Pesan Kunjungan Gratis',
    'locations.booking_success': 'Kunjungan Berhasil Dipesan!',
    'locations.booking_received': 'Spesialis kami akan menghubungi Anda dalam 24 jam.',
    'locations.details_btn': 'Lihat Detail Cabang',
    'locations.facilities': 'Fasilitas',
    'locations.contact_info': 'Info Kontak',
    'contact.form.subject_default': 'Dapatkan Pengalaman Gratis 7 Hari',
    'contact.form.error': 'Terjadi kesalahan, silakan coba lagi nanti.',
    'contact.form.success_desc': 'Terima kasih atas pertanyaan Anda, spesialis kami akan segera menghubungi Anda.',
    'contact.form.retry': 'Kirim pesan lain',
    'social.title': 'Media Sosial',
    'social.owner': 'Pemilik',
    'social.coach': 'Pelatih',
    'social.secretary1': 'Sekretaris 1',
    'social.secretary2': 'Sekretaris 2',
    'courses.reserve_btn': 'Reservasi Sekarang',
    'success.before': 'Sebelum',
    'success.after': 'Sesudah',
    'success.duration': 'Durasi',
    'coaching.philosophy_title': 'Tentang Pelatih Pribadi NEO-GYM',
    'coaching.why_title': 'Mengapa Memilih Pelatih Pribadi?',
    'coaching.science_title': 'Proses Pelatihan Ilmiah',
    'coaching.nutrition_title': 'Panduan Nutrisi Komprehensif',
    'coaching.match_title': 'Temukan Pelatih Spesialis Anda',
    'coaching.category_strength': 'Membangun Kekuatan',
    'coaching.category_sculpt': 'Membentuk Tubuh',
    'coaching.category_health': 'Pascapersalinan/Kesehatan',
    'coaching.category_special': 'Performa Olahraga',
    'coaching.select_title': 'Pilih Pelatih Anda',
    'coaching.back': '← Kembali ke kategori',
    'coaching.note': 'Catatan / Persyaratan (Opsional)',
    'ai.title': 'Pelatih Kebugaran AI',
    'ai.empty': 'Ada pertanyaan kebugaran? Tanya saya! Percakapan disimpan secara otomatis.',
    'ai.placeholder': 'Tanya tentang rencana atau teknik...',
    'ai.clear_confirm': 'Apakah Anda yakin ingin menghapus semua riwayat obrolan?',
    'ai.clear_tooltip': 'Hapus riwayat obrolan',
    'ai.error_response': 'Saya tidak dapat menjawab pertanyaan ini sekarang, silakan coba lagi nanti.',
    'ai.network_error': 'Maaf, terjadi kesalahan. Silakan periksa koneksi Anda atau coba lagi nanti.',
    'tools.title': 'Alat Kebugaran',
    'tools.bmi_title': 'Kalkulator BMI',
    'tools.bmi_subtitle': 'Asesmen Tubuh',
    'tools.hiit_title': 'Timer HIIT',
    'tools.hiit_subtitle': 'Latihan Interval',
    'tools.water_title': 'Air Harian',
    'tools.water_subtitle': 'Pelacakan Hidrasi',
    'tools.height': 'Tinggi (cm)',
    'tools.weight': 'Berat (kg)',
    'tools.calculate_bmi': 'Hitung BMI',
    'tools.bmi_underweight': 'Berat Kurang',
    'tools.bmi_normal': 'Normal',
    'tools.bmi_overweight': 'Kelebihan Berat',
    'tools.bmi_obese1': 'Obesitas I',
    'tools.bmi_obese2': 'Obesitas II',
    'tools.bmi_obese3': 'Obesitas III',
    'tools.work': 'Kerja (det)',
    'tools.rest': 'Istirahat (det)',
    'tools.rounds': 'Putaran',
    'tools.working': '🔥🔥 Sedang Bekerja',
    'tools.resting': '🧊🧊 Sedang Istirahat',
    'tools.water_goal_desc': 'Asupan harian yang disarankan 2000ml+ (sekitar 8 gelas)',
    'tools.water_achieved': 'Target Tercapai! Terhidrasi Baik 💧',
    'games.hurdles.instructions': 'Gunakan Tombol Panah ↑ ↓ ← → untuk menghindari rintangan!',
    'games.hurdles.static': 'Statis',
    'games.hurdles.moving': 'Bergerak Naik/Turun',
    'games.hurdles.enter': 'Masuk Level',
    'games.hurdles.level_easy': 'Mudah',
    'games.hurdles.level_medium': 'Sedang',
    'games.hurdles.level_hard': 'Sulit',
    'games.hurdles.desc_easy': 'Sedikit rintangan / Kecepatan lambat',
    'games.hurdles.desc_medium': 'Kepadatan sedang / Kecepatan standar',
    'games.hurdles.desc_hard': 'Kepadatan tinggi / Bergerak cepat',
    'games.hurdles.retry': 'Coba Lagi',
    'games.hurdles.again': 'Lari Lagi',
    'games.sprint.instructions': 'Gunakan A/D secara bergantian untuk lari cepat! Bersaing dengan 5 AI elit. Mendukung jarak 100m & 200m.',
    'games.sprint.enter': 'Bersiap Balapan',
    'games.sprint.classic': 'Neon Klasik',
    'games.sprint.volcano': 'Gurun Vulkanik',
    'games.sprint.jungle': 'Hutan Siber',
    'games.sprint.deepsea': 'Tekanan Laut Dalam',
    'games.sprint.back_main': 'Kembali ke Menu',
    'games.sprint.sprint_100': 'Sprint Ekstrem',
    'games.sprint.sprint_200': 'Ledakan Daya Tahan',
    'games.sprint.reselect_env': 'Pilih Ulang Lingkungan',
    'games.sprint.again': 'Balapan Lagi',
    'games.sprint.runner': 'Pelari AI',
    'success.title': 'Kisah Sukses',
    'success.details_title': 'Detail Transformasi',
    'success.cta': 'Saya juga ingin memesan rencana pengalaman',
    'contact.title': 'Hubungi Kami',
    'contact.subtitle': 'Siap untuk memulai jalan kekuatan Anda? Tinggalkan info kontak Anda dan konsultan kami akan menghubungi dalam 24 jam.',
    'contact.form.name': 'Nama Lengkap',
    'contact.form.phone': 'Nomor Telepon',
    'contact.form.email': 'Alamat Email',
    'contact.form.subject': 'Subjek Pertanyaan',
    'contact.form.message': 'Isi Pesan',
    'contact.form.submit': 'Kirim Pesan Pertanyaan',
    'contact.form.success': 'Pesan Berhasil Terkirim',
    'contact.info.address': 'Alamat Perusahaan',
    'contact.info.phone': 'Hotline Pertanyaan',
    'contact.info.email': 'Email',
    'contact.info.hours': 'Jam Layanan',
    'courses.title': 'Kursus Pelatihan Pro',
    'courses.subtitle': 'Beragam kursus intensitas tinggi berdasarkan tujuan Anda, dari pemahatan inti hingga peningkatan daya.',
    'courses.target_group': 'Grup Target',
    'courses.goals_title': 'Tujuan Kursus',
    'courses.details_title': 'Detail Kursus',
    'courses.duration_label': 'Estimasi Durasi:',
    'courses.book_now': 'Pesan Pengalaman Sekarang',
    'story.lin.name': 'Bpk. Lin',
    'story.lin.story': 'Turun 15kg dan bertambah 5kg otot dalam 6 bulan di NEO-GYM.',
    'story.lin.details': 'Bpk. Lin mengabaikan kesehatannya karena jadwal yang sibuk. Dengan bimbingan pelatih, ia memulai latihan kekuatan dua kali seminggu dan kontrol diet yang ketat.',
    'story.chang.name': 'Ibu Chang',
    'story.chang.story': 'Turun 3kg dan menyelesaikan maraton pertamanya dalam 12 bulan di NEO-GYM.',
    'story.chang.details': 'Ibu Chang awalnya kurang percaya diri dengan lingkungan gym. Dibimbing oleh pelatih, ia mengembangkan daya tahan selama 12 bulan untuk mencapai garis finish maraton.',
    'story.wang.name': 'Bpk. Wang',
    'story.wang.story': 'Turun 6kg dan menghilangkan sakit punggung kronis dalam 8 bulan di NEO-GYM.',
    'story.wang.details': 'Sebagai insinyur, Bpk. Wang menderita sakit punggung kronis. Melalui latihan fungsional selama 8 bulan, ia memperkuat otot inti dan hidup tanpa rasa sakit.',
    'story.lee.name': 'Ibu Lee',
    'story.lee.story': 'Mengurangi lemak tubuh sebesar 8% dan mendapatkan kembali kepercayaan diri setelah melahirkan dalam 10 bulan di NEO-GYM.',
    'story.lee.details': 'Ibu Lee berjuang dengan berat badan pascapersalinan. Pelatihan pribadi dan konsultasi nutrisi membantunya mencapai bentuk tubuh terbaiknya kembali.',
  },
  'ja': {
    'brand': 'NEO-GYM プロフィットネス',
    'nav.home': 'ホーム',
    'nav.about': 'について',
    'nav.features': '特徴',
    'nav.courses': 'コース',
    'nav.coaching': 'コーチ',
    'nav.schedule': 'スケジュール',
    'nav.locations': '店舗',
    'nav.membership': 'メンバーシップ',
    'nav.contact': 'お問い合わせ',
    'nav.login': 'ログイン',
    'hero.title': '限界を超えろ',
    'hero.subtitle': '自分を越えろ',
    'hero.description': '最先端の設備、究極の空間、プロのコーチ陣。あなたの進化のために。',
    'hero.start': '追跡開始',
    'hero.explore': '無料体験',
    'hero.contact': 'カウンセリング予約',
    'features.title': '最高の施設',
    'features.tag': '最高の施設',
    'features.cardio.title': '高機能有酸素エリア',
    'features.cardio.desc': 'リアルタイムデータ同期対応のランニングマシン完備。',
    'features.strength.title': '高重量負荷エリア',
    'features.strength.desc': '多数のスクワットラックとプロ仕様のリフティング機材。',
    'features.functional.title': 'ファンクショナルトレーニング',
    'features.functional.desc': '人工芝、スレッド、バトルロープで機能性を向上。',
    'schedule.title': 'クラススケジュール',
    'schedule.tag': 'グループクラス',
    'schedule.mon': '月',
    'schedule.tue': '火',
    'schedule.wed': '水',
    'schedule.thu': '木',
    'schedule.fri': '金',
    'schedule.sat': '土',
    'schedule.sun': '日',
    'schedule.detail': '詳細を見る',
    'schedule.booking': '今すぐ予約',
    'schedule.success': '予約が完了しました！',
    'locations.title': '全国の拠点',
    'locations.tag': '各店舗',
    'locations.search': '店舗を探す...',
    'locations.visit': '無料見學予約',
    'locations.full_schedule': '全スケジュール',
    'coaching.title': 'パーソナルトレーニング',
    'coaching.tag': 'パーソナル',
    'coaching.more': '詳細はこちら',
    'coaching.find': 'トレーナーを探す',
    'coaching.reserve': '体験・相談予約',
    'footer.rights': '© 2026 NEO-GYM. All rights reserved.',
    'common.name': '氏名',
    'common.phone': '電話番号',
    'common.email': 'メール',
    'common.submit': '送信する',
    'schedule.booking_title': '予約情報の入力',
    'schedule.booking_success': 'クラスの予約が完了しました！',
    'schedule.booking_received': '予約リクエストを受け付けました。',
    'schedule.instructor': '担当インストラクター',
    'schedule.level': '推奨レベル',
    'schedule.intro': 'コース紹介',
    'locations.booking_title': '無料見学予約',
    'locations.booking_success': '見学予約が完了しました！',
    'locations.booking_received': '担当者より24時間以内にご連絡いたします。',
    'locations.details_btn': '店舗詳細を見る',
    'locations.facilities': '館内施設',
    'locations.contact_info': '連絡先情報',
    'contact.form.subject_default': '無料7日間体験プランを申し込む',
    'contact.form.error': 'エラーが発生しました。後でもう一度お試しください。',
    'contact.form.success_desc': 'お問い合わせありがとうございます。担当者より折り返しご連絡いたします。',
    'contact.form.retry': '別のメッセージを送る',
    'social.title': 'ソーシャルメディア',
    'social.owner': 'オーナー',
    'social.coach': 'コーチ',
    'social.secretary1': '秘書1',
    'social.secretary2': '秘書2',
    'courses.reserve_btn': '今すぐ予約',
    'success.before': 'Before',
    'success.after': 'After',
    'success.duration': '期間',
    'coaching.philosophy_title': 'NEO-GYMのパーソナルトレーニングについて',
    'coaching.why_title': 'なぜパーソナルトレーナーを選ぶのか？',
    'coaching.science_title': '科学的なトレーニングプロセス',
    'coaching.nutrition_title': '包括的な栄養指導',
    'coaching.match_title': 'あなたの専属コーチを見つける',
    'coaching.category_strength': '筋力アップ',
    'coaching.category_sculpt': 'ボディメイキング',
    'coaching.category_health': '産後・ヘルスケア',
    'coaching.category_special': '競技力向上',
    'coaching.select_title': 'コーチを選択',
    'coaching.back': '← カテゴリに戻る',
    'coaching.note': '備考 / ご要望（任意）',
    'ai.title': 'AI フィットネスコーチ',
    'ai.empty': 'フィットネスに関する質問はありますか？私に聞いてください！会話は自動的に保存されます。',
    'ai.placeholder': 'プランやテクニックについて聞く...',
    'ai.clear_confirm': 'すべてのチャット履歴を消去してもよろしいですか？',
    'ai.clear_tooltip': 'チャット履歴を消去',
    'ai.error_response': '現在、この質問にはお答えできません。後でもう一度お試しください。',
    'ai.network_error': '申し訳ありません。エラーが発生しました。接続を確認するか、後でもう一度お試しください。',
    'tools.title': 'フィットネスツール',
    'tools.bmi_title': 'BMI 計算機',
    'tools.bmi_subtitle': '体態評価',
    'tools.hiit_title': 'HIIT タイマー',
    'tools.hiit_subtitle': 'インターバルトレーニング',
    'tools.water_title': '毎日の飲水',
    'tools.water_subtitle': '水分追跡',
    'tools.height': '身長 (cm)',
    'tools.weight': '体重 (kg)',
    'tools.calculate_bmi': 'BMIを計算する',
    'tools.bmi_underweight': '低体重',
    'tools.bmi_normal': '標準',
    'tools.bmi_overweight': '肥満気味',
    'tools.bmi_obese1': '肥満（1度）',
    'tools.bmi_obese2': '肥満（2度）',
    'tools.bmi_obese3': '肥満（3度）',
    'tools.work': 'ワーク（秒）',
    'tools.rest': 'レスト（秒）',
    'tools.rounds': 'ラウンド数',
    'tools.working': '🔥🔥 トレーニング中',
    'tools.resting': '🧊🧊 休憩中',
    'tools.water_goal_desc': '1日2000ml以上の水分摂取（約8杯）を推奨します',
    'tools.water_achieved': '目標達成！水分補給はバッチリです 💧',
    'games.hurdles.instructions': '矢印キー ↑ ↓ ← → を使って障害物を避けよう！',
    'games.hurdles.static': '固定',
    'games.hurdles.moving': '上下移動',
    'games.hurdles.enter': 'レベルに入る',
    'games.hurdles.level_easy': '簡単',
    'games.hurdles.level_medium': '普通',
    'games.hurdles.level_hard': '難しい',
    'games.hurdles.desc_easy': '障害物少なめ / 低速',
    'games.hurdles.desc_medium': '標準密度 / 標準速度',
    'games.hurdles.desc_hard': '高密度 / 高速',
    'games.hurdles.retry': 'リトライ',
    'games.hurdles.again': 'もう一度走る',
    'games.sprint.instructions': 'AキーとDキーを交互に叩いてダッシュ！5人のエリートAIと競い合おう。100mと200mに対応。',
    'games.sprint.enter': '準備開始',
    'games.sprint.classic': 'クラシックネオン',
    'games.sprint.volcano': 'ボルケーノ原野',
    'games.sprint.jungle': 'サイバージャングル',
    'games.sprint.deepsea': 'ディープシー・プレッシャー',
    'games.sprint.back_main': 'メインメニューに戻る',
    'games.sprint.sprint_100': 'エクストリーム・スプリント',
    'games.sprint.sprint_200': 'エンデュランス・バースト',
    'games.sprint.reselect_env': '環境を再選択',
    'games.sprint.again': 'もう一度レース',
    'games.sprint.runner': 'AIランナー',
    'success.title': '成功事例',
    'success.details_title': '変遷の詳細',
    'success.cta': '体験プランを予約する',
    'contact.title': 'お問い合わせ',
    'contact.subtitle': '強者への道を歩む準備はできましたか？連絡先をご記入ください。24時間以内に専門アドバイザーがご連絡いたします。',
    'contact.form.name': 'お名前',
    'contact.form.phone': '電話番号',
    'contact.form.email': 'メールアドレス',
    'contact.form.subject': 'お問い合わせ件名',
    'contact.form.message': 'メッセージ内容',
    'contact.form.submit': 'お問い合わせを送信',
    'contact.form.success': '送信が完了しました',
    'contact.info.address': '会社住所',
    'contact.info.phone': '相談専用ダイヤル',
    'contact.info.email': 'メール',
    'contact.info.hours': 'サービス時間',
    'courses.title': 'プロトレーニングコース',
    'courses.subtitle': 'コアの彫刻から瞬発力の向上まで、目標に合わせた多様な高強度プログラムを用意しています。',
    'courses.target_group': '対象者',
    'courses.goals_title': 'トレーニング目標',
    'courses.details_title': 'コース詳細',
    'courses.duration_label': '予想時間：',
    'courses.book_now': '今すぐ体験予約',
    'story.lin.name': '林様',
    'story.lin.story': 'NEO-GYMでの6ヶ月間のトレーニングで、15kgの減量と5kgの筋肉増量に成功。',
    'story.lin.details': '多忙なスケジュールで健康を疎かにしていた林様ですが、コーチの指導のもと週2回の筋力トレーニングと厳格な食事管理を開始し、数値と体力が劇的に改善しました。',
    'story.chang.name': '張様',
    'story.chang.story': 'NEO-GYMでの12ヶ月間のトレーニングで、3kg減量し、初のハーフマラソンを完走。',
    'story.chang.details': '最初はジムに通うことに不安を感じていた張様。12ヶ月かけて基礎体力と心肺機能を段階的に高めることで、マラソン完走という大きな目標を達成しました。',
    'story.wang.name': '王様',
    'story.wang.story': 'NEO-GYMでの8ヶ月間のトレーニングで、6kg減量し、長年の腰痛を完全に克服。',
    'story.wang.details': 'エンジニアという職業柄、慢性的な腰痛に悩まされていた王様。ファンクショナルトレーニングで深層筋肉を鍛えることで、痛みから解放され可動域も広がりました。',
    'story.lee.name': '李様',
    'story.lee.story': 'NEO-GYMでの10ヶ月間のトレーニングで、体脂肪率を8%減少させ、産後の自信を回復。',
    'story.lee.details': '産後の体型変化に悩んでいた李様。栄養指導とトレーニングを並行することで、代謝機能を高め、以前よりも引き締まった理想のスタイルを手に入れました。',
  },
  'ko': {
    'brand': 'NEO-GYM 프로 피트니스',
    'nav.home': '홈',
    'nav.about': '소개',
    'nav.features': '특징',
    'nav.courses': '코스',
    'nav.coaching': '코칭',
    'nav.schedule': '스케줄',
    'nav.locations': '지점',
    'nav.membership': '멤버십',
    'nav.contact': '문의하기',
    'nav.login': '로그인',
    'hero.title': '한계를 넘어라',
    'hero.subtitle': '자신을 초월하라',
    'hero.description': '최고급 장비, 궁극의 공간, 전문 코치진. 당신의 진화를 위해 탄생했습니다.',
    'hero.start': '기록 시작',
    'hero.explore': '무료 체험',
    'hero.contact': '상담 예약',
    'features.title': '최고의 시설',
    'features.tag': '최고의 시설',
    'features.cardio.title': '고급 유산소 구역',
    'features.cardio.desc': '실시간 데이터 동기화가 가능한 프리미엄 유산소 장비.',
    'features.strength.title': '중량 저항 구역',
    'features.strength.desc': '다양한 스쿼트 랙과 전문 파워리프팅 장비.',
    'features.functional.title': '기능성 트레이닝',
    'features.functional.desc': '인조잔디, 슬레드, 배틀로프로 기능성 강화.',
    'schedule.title': '그룹 클래스 시간표',
    'schedule.tag': '그룹 클래스',
    'schedule.mon': '월',
    'schedule.tue': '화',
    'schedule.wed': '수',
    'schedule.thu': '목',
    'schedule.fri': '금',
    'schedule.sat': '토',
    'schedule.sun': '일',
    'schedule.detail': '자세히 보기',
    'schedule.booking': '지금 예약하기',
    'schedule.success': '예약이 완료되었습니다!',
    'locations.title': '전국 지점 안내',
    'locations.tag': '지점 안내',
    'locations.search': '지점 검색...',
    'locations.visit': '무료 방문 예약',
    'locations.full_schedule': '전체 시간표',
    'coaching.title': '개인 트레이닝',
    'coaching.tag': '퍼스널 트레이닝',
    'coaching.more': '자세히 보기',
    'coaching.find': '트레이너 찾기',
    'coaching.reserve': '상담 예약하기',
    'footer.rights': '© 2026 NEO-GYM. All rights reserved.',
    'common.name': '이름',
    'common.phone': '전화번호',
    'common.email': '이메일',
    'common.submit': '제출하기',
    'schedule.booking_title': '예약 정보 입력',
    'schedule.booking_success': '클래스 예약이 완료되었습니다!',
    'schedule.booking_received': '예약 요청이 접수되었습니다.',
    'schedule.instructor': '담당 강사',
    'schedule.level': '권장 레벨',
    'schedule.intro': '코스 소개',
    'locations.booking_title': '무료 방문 예약',
    'locations.booking_success': '방문 예약이 완료되었습니다!',
    'locations.booking_received': '담당자가 24시간 이내에 연락드리겠습니다.',
    'locations.details_btn': '지점 상세 보기',
    'locations.facilities': '지점 시설',
    'locations.contact_info': '연락처 정보',
    'contact.form.subject_default': '무료 7일 체험 플랜 받기',
    'contact.form.error': '오류가 발생했습니다. 나중에 다시 시도해 주세요.',
    'contact.form.success_desc': '문의해 주셔서 감사합니다. 담당자가 곧 연락드리겠습니다.',
    'contact.form.retry': '다른 메시지 보내기',
    'social.title': '소셜 미디어',
    'social.owner': '대표',
    'social.coach': '코치',
    'social.secretary1': '비서 1',
    'social.secretary2': '비서 2',
    'courses.reserve_btn': '지금 예약하기',
    'success.before': 'Before',
    'success.after': 'After',
    'success.duration': '기간',
    'coaching.philosophy_title': 'NEO-GYM 퍼스널 트레이닝 소개',
    'coaching.why_title': '왜 퍼스널 트레이너를 선택해야 할까요?',
    'coaching.science_title': '과학적인 트레이닝 프로세스',
    'coaching.nutrition_title': '종괄적인 영양 지도',
    'coaching.match_title': '나만의 전담 코치 찾기',
    'coaching.category_strength': '근력 증진',
    'coaching.category_sculpt': '체형 조각',
    'coaching.category_health': '산후/건강 관리',
    'coaching.category_special': '전문 운동 강화',
    'coaching.select_title': '코치 선택하기',
    'coaching.back': '← 카테고리로 돌아가기',
    'coaching.note': '비고 / 요청 사항 (선택)',
    'ai.title': 'AI 운동 코치',
    'ai.empty': '운동에 대해 궁금한 점이 있으신가요? 제게 물어보세요! 대화는 자동으로 저장됩니다.',
    'ai.placeholder': '계획이나 테크닉에 대해 물어보세요...',
    'ai.clear_confirm': '모든 채팅 기록을 삭제하시겠습니까?',
    'ai.clear_tooltip': '채팅 기록 삭제',
    'ai.error_response': '지금은 질문에 답할 수 없습니다. 나중에 다시 시도해 주세요.',
    'ai.network_error': '죄송합니다. 오류가 발생했습니다. 연결을 확인하거나 나중에 다시 시도해 주세요.',
    'tools.title': '피트니스 보조 도구',
    'tools.bmi_title': 'BMI 계산기',
    'tools.bmi_subtitle': '체형 평가',
    'tools.hiit_title': 'HIIT 타이머',
    'tools.hiit_subtitle': '인터벌 트레이닝',
    'tools.water_title': '오늘의 수분',
    'tools.water_subtitle': '수분 추적',
    'tools.height': '키 (cm)',
    'tools.weight': '몸무게 (kg)',
    'tools.calculate_bmi': 'BMI 지수 계산기',
    'tools.bmi_underweight': '저체중',
    'tools.bmi_normal': '정상 범위',
    'tools.bmi_overweight': '과체중',
    'tools.bmi_obese1': '경도 비만',
    'tools.bmi_obese2': '중등도 비만',
    'tools.bmi_obese3': '고도 비만',
    'tools.work': '운동 (초)',
    'tools.rest': '휴식 (초)',
    'tools.rounds': '세트 수',
    'tools.working': '🔥🔥 운동 중',
    'tools.resting': '🧊🧊 휴식 중',
    'tools.water_goal_desc': '하루 2000ml 이상의 수분 섭취를 권장합니다 (약 8잔)',
    'tools.water_achieved': '목표 달성! 수분 충전 완료 💧',
    'games.hurdles.instructions': '방향키 ↑ ↓ ← → 를 사용하여 장애물을 피하세요!',
    'games.hurdles.static': '고정형',
    'games.hurdles.moving': '상하 이동형',
    'games.hurdles.enter': '레벨 시작',
    'games.hurdles.level_easy': '쉬움',
    'games.hurdles.level_medium': '보통',
    'games.hurdles.level_hard': '어려움',
    'games.hurdles.desc_easy': '장애물 적음 / 느린 속도',
    'games.hurdles.desc_medium': '보통 밀도 / 표준 속도',
    'games.hurdles.desc_hard': '높은 밀도 / 빠른 속도',
    'games.hurdles.retry': '다시 시도',
    'games.hurdles.again': '다시 달리기',
    'games.sprint.instructions': 'A/D 키를 번갈아 눌러 질주하세요! 5명의 엘리트 AI와 경쟁하세요. 100m 및 200m 지원.',
    'games.sprint.enter': '준비하기',
    'games.sprint.classic': '클래식 네온',
    'games.sprint.volcano': '화산 황무지',
    'games.sprint.jungle': '사이버 정글',
    'games.sprint.deepsea': '심해 어비스',
    'games.sprint.back_main': '메인 메뉴로 돌아가기',
    'games.sprint.sprint_100': '익스트림 스프린트',
    'games.sprint.sprint_200': '지구력 폭발',
    'games.sprint.reselect_env': '환경 다시 선택하기',
    'games.sprint.again': '다시 경기하기',
    'games.sprint.runner': 'AI 러너',
    'success.title': '성공 사례',
    'success.details_title': '변화 상세 내용',
    'success.cta': '나도 체험 플랜 예약하기',
    'contact.title': '문의하기',
    'contact.subtitle': '강자의 길을 시작할 준비가 되셨나요? 연락처를 남겨주시면 24시간 이내에 전문 상담원이 연락드리겠습니다.',
    'contact.form.name': '이름',
    'contact.form.phone': '연락처',
    'contact.form.email': '이메일 주소',
    'contact.form.subject': '문의 주제',
    'contact.form.message': '메시지 내용',
    'contact.form.submit': '문의 메시지 전송',
    'contact.form.success': '메시지가 전송되었습니다',
    'contact.info.address': '회사 주소',
    'contact.info.phone': '상담 전용 전화',
    'contact.info.email': '이메일',
    'contact.info.hours': '서비스 시간',
    'courses.title': '전문 트레이닝 코스',
    'courses.subtitle': '코어 강화부터 폭발적인 힘 향상까지, 목표에 맞는 다양한 고강도 코스를 제공합니다.',
    'courses.target_group': '대상',
    'courses.goals_title': '수업 목표',
    'courses.details_title': '수업 상세',
    'courses.duration_label': '예상 소요 시간:',
    'courses.book_now': '지금 체험 예약하기',
    'story.lin.name': '임 선생',
    'story.lin.story': 'NEO-GYM에서 6개월간 훈련하여 15kg 감량 및 5kg 근육 증량 성공.',
    'story.lin.details': '바쁜 일정으로 건강을 소홀히 했던 임 선생은 코치의 지도 아래 주 2회 근력 운동과 철저한 식단 관리를 시작하여 체력과 건강 지표를 크게 개선했습니다.',
    'story.chang.name': '장 여사',
    'story.chang.story': 'NEO-GYM에서 12개월간 훈련하여 3kg 감량 및 첫 하프 마라톤 완주 성공.',
    'story.chang.details': '운동 기초가 부족했던 장 여사는 코치와 함께 12개월간 심폐 지구력을 꾸준히 길러 생애 첫 하프 마라톤 완주라는 쾌거를 이루었습니다.',
    'story.wang.name': '왕 선생',
    'story.wang.story': 'NEO-GYM에서 8개월간 훈련하여 6kg 감량 및 만성 허리 통증 완전 해결.',
    'story.wang.details': '엔지니어로 근무하며 긴 시간 앉아 있어 발생한 허리 통증을 기능성 트레이닝과 코어 강화를 통해 8개월 만에 완벽히 극복했습니다.',
    'story.lee.name': '이 여사',
    'story.lee.story': 'NEO-GYM에서 10개월간 훈련하여 체지방 8% 감소 및 산후 자신감 회복 성공.',
    'story.lee.details': '산후 체중 변화로 고민하던 이 여사는 맞춤형 운동과 영양 컨설팅을 통해 건강한 대사 능력을 되찾고 자신감 넘치는 체형을 완성했습니다.',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [currentLang, setCurrentLang] = useState<Language>(LANGUAGES[0]);

  const setLanguage = (code: LanguageCode) => {
    const lang = LANGUAGES.find(l => l.code === code);
    if (lang) setCurrentLang(lang);
  };

  const t = (key: string): string => {
    return TRANSLATIONS[currentLang.code][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLang, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
