import React, { createContext, useContext, useState, ReactNode } from 'react';

export type LanguageCode = 'zh-TW' | 'en' | 'vi' | 'id' | 'ja' | 'ko';

export interface Language {
  code: LanguageCode;
  name: string;
  flag: string;
}

export const LANGUAGES: Language[] = [
  { code: 'zh-TW', name: '繁體中文', flag: '🇹🇼' },
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'vi', name: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'id', name: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'ja', name: '日本語', flag: '🇯🇵' },
  { code: 'ko', name: '한국어', flag: '🇰🇷' }
];

interface LanguageContextType {
  currentLang: Language;
  setLanguage: (code: LanguageCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  'zh-TW': {
    'brand': 'NEO-GYM 競技健身房',
    'nav.home': '首頁',
    'nav.about': '關於我們',
    'nav.features': '特色',
    'nav.courses': '課程',
    'nav.coaching': '私人教練',
    'nav.schedule': '課表',
    'nav.locations': '分店',
    'nav.contact': '聯絡我們',
    'nav.login': '登入會員',
    'hero.title': '超越極限，定義自我',
    'hero.subtitle': '超越自我',
    'hero.description': '最頂尖的器材、極致的場域、專業的教練團隊，為您的進化而生。',
    'hero.start': '進入追蹤系統',
    'hero.explore': '領取免費體驗',
    'hero.contact': '聯絡專員諮詢',
    'features.title': '頂級運動設施',
    'features.tag': 'Prime Facilities',
    'features.cardio.title': '高階心肺區',
    'features.cardio.desc': '配備頂級跑步機與飛輪，支援即時數據同步。',
    'features.strength.title': '重型阻力區',
    'features.strength.desc': '多組深蹲架與專業健力器材，打造極致力量。',
    'features.functional.title': '多功能訓練',
    'features.functional.desc': '草皮區、雪橇、戰繩，提升功能性體能。',
    'schedule.title': '團體課程課表',
    'schedule.tag': 'Group Classes',
    'schedule.mon': 'Mon',
    'schedule.tue': 'Tue',
    'schedule.wed': 'Wed',
    'schedule.thu': 'Thu',
    'schedule.fri': 'Fri',
    'schedule.sat': 'Sat',
    'schedule.sun': 'Sun',
    'schedule.detail': '查看詳情',
    'schedule.booking': '立即預約課程',
    'schedule.success': '課程預約成功！',
    'locations.title': '全國連鎖據點',
    'locations.tag': 'Our Locations',
    'locations.search': '搜尋分店...',
    'locations.visit': '預約免費參觀',
    'locations.full_schedule': '看完整課表',
    'coaching.title': '私人健身教練',
    'coaching.tag': 'Personal Training',
    'coaching.more': '了解更多',
    'coaching.find': '尋找私人教練',
    'coaching.reserve': '立即預約諮詢體驗',
    'footer.rights': '© 2026 NEO-GYM. 版權所有。',
    'common.name': '姓名',
    'common.phone': '電話',
    'common.email': 'Email',
    'common.submit': '確認送出',
    'schedule.booking_title': '填寫預約資訊',
    'schedule.booking_success': '課程預約成功！',
    'schedule.booking_received': '我們已收到您的預約申請。',
    'schedule.instructor': '授課教練',
    'schedule.level': '建議等級',
    'schedule.intro': '課程介紹',
    'locations.booking_title': '預約免費參觀',
    'locations.booking_success': '參觀預約成功！',
    'locations.booking_received': '專員將於 24 小時內與您聯繫。',
    'locations.details_btn': '查看分店詳情',
    'locations.facilities': '館內設施',
    'locations.contact_info': '聯絡資訊',
    'contact.form.subject_default': '領取免費 7 日體驗計畫',
    'contact.form.error': '發生錯誤，請稍後再試。',
    'contact.form.success_desc': '感謝您的諮詢，專人將盡快與您聯繫。',
    'contact.form.retry': '再傳送一則訊息',
    'social.title': '社交媒體',
    'social.owner': '公司負責人',
    'social.coach': '教練',
    'courses.reserve_btn': '立即預約',
    'success.before': 'Before',
    'success.after': 'After',
    'success.duration': '持續時間',
    'coaching.philosophy_title': '關於 NEO-GYM 私人教練',
    'coaching.why_title': '為什麼選擇私人教練？',
    'coaching.science_title': '科學化的訓練流程',
    'coaching.nutrition_title': '全方位的營養指導',
    'coaching.match_title': '尋找您的專屬教練',
    'coaching.category_strength': '力量增長組',
    'coaching.category_sculpt': '體態雕塑組',
    'coaching.category_health': '產後/健康組',
    'coaching.category_special': '專項運動強化',
    'coaching.select_title': '選擇您的教練',
    'coaching.back': '← 返回組別選擇',
    'coaching.note': '備註 / 需求 (選填)',
    'ai.title': 'AI 運動教練',
    'ai.empty': '有任何運動或健身問題嗎？儘管問我！對話將自動保存。',
    'ai.placeholder': '問問如何制定計畫或改善動作...',
    'ai.clear_confirm': '確定要清除所有聊天紀錄嗎？',
    'ai.clear_tooltip': '清除對話紀錄',
    'ai.error_response': '我現在無法回答這個問題，請稍候再試。',
    'ai.network_error': '抱歉，發生了錯誤。請檢查您的網路連線或稍後再試。',
    'tools.title': '健身輔助工具',
    'tools.bmi_title': 'BMI 計算機',
    'tools.bmi_subtitle': '體態評估',
    'tools.hiit_title': 'HIIT 計時器',
    'tools.hiit_subtitle': '間歇訓練',
    'tools.water_title': '每日飲水',
    'tools.water_subtitle': '水分追蹤',
    'tools.height': '身高 (cm)',
    'tools.weight': '體重 (kg)',
    'tools.calculate_bmi': '計算 BMI 指數',
    'tools.bmi_underweight': '體重過輕',
    'tools.bmi_normal': '正常範圍',
    'tools.bmi_overweight': '過重',
    'tools.bmi_obese1': '輕度肥胖',
    'tools.bmi_obese2': '中度肥胖',
    'tools.bmi_obese3': '重度肥胖',
    'tools.work': '工作 (秒)',
    'tools.rest': '休息 (秒)',
    'tools.rounds': '組數',
    'tools.working': '🔥🔥 運動中',
    'tools.resting': '🧊🧊 休息中',
    'tools.water_goal_desc': '建議每日攝取 2000ml 以上的水分 (約 8 杯)',
    'tools.water_achieved': '目標達成！今日水分充沛 💧',
    'games.hurdles.instructions': '使用方向鍵 ↑ ↓ ← → 躲避障礙！',
    'games.hurdles.static': '固定不動',
    'games.hurdles.moving': '會上下移動',
    'games.hurdles.enter': '進入關卡',
    'games.hurdles.level_easy': '簡單',
    'games.hurdles.level_medium': '適中',
    'games.hurdles.level_hard': '困難',
    'games.hurdles.desc_easy': '障礙物極少 / 慢速',
    'games.hurdles.desc_medium': '一般密度 / 標準速度',
    'games.hurdles.desc_hard': '高密度 / 快速移動',
    'games.hurdles.retry': '重新嘗試',
    'games.hurdles.again': '再跑一回',
    'games.sprint.instructions': '交替連打 A/D 啟動衝刺！與五位頂尖 AI 同場競技，體驗不同賽程的極致爆發。現在支援 100m 與 200m 距離。',
    'games.sprint.enter': '進入備戰',
    'games.sprint.classic': '經典霓虹',
    'games.sprint.volcano': '熔岩荒原',
    'games.sprint.jungle': '網絡叢林',
    'games.sprint.deepsea': '深海壓力',
    'games.sprint.back_main': '返回主選單',
    'games.sprint.sprint_100': '極速衝刺',
    'games.sprint.sprint_200': '耐力爆發',
    'games.sprint.reselect_env': '重新選擇環境',
    'games.sprint.again': '再賽一場',
    'games.sprint.runner': 'AI 跑者',
    'success.title': '學員蛻變見證',
    'success.details_title': '學員蛻變詳情',
    'success.cta': '我也要預約體驗計畫',
    'contact.title': '聯絡我們',
    'contact.subtitle': '準備好開始您的強者之路了嗎？留下聯絡資訊，我們的顧問將在 24 小時內與您聯繫。',
    'contact.form.name': '中文姓名',
    'contact.form.phone': '聯絡電話',
    'contact.form.email': '電子郵件',
    'contact.form.subject': '諮詢主題',
    'contact.form.message': '訊息內容',
    'contact.form.submit': '傳送諮詢訊息',
    'contact.form.success': '訊息已成功傳送',
    'contact.info.address': '公司地址',
    'contact.info.phone': '諮詢專線',
    'contact.info.email': '電子郵件',
    'contact.info.hours': '服務時間',
    'courses.title': '專業訓練課程',
    'courses.subtitle': '根據您的目標，提供多樣化的高強度課程，從核心雕塑到爆發力提升，全面釋放潛能。',
    'courses.target_group': '針對族群',
    'courses.goals_title': '課程目標',
    'courses.details_title': '課程詳情',
    'courses.duration_label': '預計時長：',
    'courses.book_now': '立即預約體驗'
  },
  'en': {
    'brand': 'NEO-GYM Pro Fitness',
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.features': 'Features',
    'nav.courses': 'Courses',
    'nav.coaching': 'Coaching',
    'nav.schedule': 'Schedule',
    'nav.locations': 'Locations',
    'nav.contact': 'Contact',
    'nav.login': 'Login',
    'hero.title': 'BREAK LIMITS, DEFINE SELF',
    'hero.subtitle': 'EXCEED YOURSELF',
    'hero.description': 'Top-tier equipment, ultimate spaces, professional coaches, born for your evolution.',
    'hero.start': 'Start Tracking',
    'hero.explore': 'Free Trial',
    'hero.contact': 'Contact Counselor',
    'features.title': 'Prime Facilities',
    'features.tag': 'Prime Facilities',
    'features.cardio.title': 'Advanced Cardio',
    'features.cardio.desc': 'Top-tier treadmills and bikes with real-time data sync.',
    'features.strength.title': 'Heavy Resistance',
    'features.strength.desc': 'Multiple squat racks and professional powerlifting gear.',
    'features.functional.title': 'Functional Training',
    'features.functional.desc': 'Turf, sleds, and battle ropes for functional fitness.',
    'schedule.title': 'Class Schedule',
    'schedule.tag': 'Group Classes',
    'schedule.mon': 'Mon',
    'schedule.tue': 'Tue',
    'schedule.wed': 'Wed',
    'schedule.thu': 'Thu',
    'schedule.fri': 'Fri',
    'schedule.sat': 'Sat',
    'schedule.sun': 'Sun',
    'schedule.detail': 'View Details',
    'schedule.booking': 'Book Class Now',
    'schedule.success': 'Booking Successful!',
    'locations.title': 'Nationwide Branch',
    'locations.tag': 'Our Locations',
    'locations.search': 'Search branches...',
    'locations.visit': 'Book Free Visit',
    'locations.full_schedule': 'Full Schedule',
    'coaching.title': 'Private Coaching',
    'coaching.tag': 'Personal Training',
    'coaching.more': 'Learn More',
    'coaching.find': 'Find a Coach',
    'coaching.reserve': 'Reserve Consultation',
    'footer.rights': '© 2026 NEO-GYM. All rights reserved.',
    'common.name': 'Name',
    'common.phone': 'Phone',
    'common.email': 'Email',
    'common.submit': 'Submit',
    'schedule.booking_title': 'Booking Information',
    'schedule.booking_success': 'Class Booked Successfully!',
    'schedule.booking_received': 'We have received your booking request.',
    'schedule.instructor': 'Instructor',
    'schedule.level': 'Level',
    'schedule.intro': 'Introduction',
    'locations.booking_title': 'Book a Free Visit',
    'locations.booking_success': 'Visit Booked Successfully!',
    'locations.booking_received': 'Our specialist will contact you within 24 hours.',
    'locations.details_btn': 'View Branch Details',
    'locations.facilities': 'Facilities',
    'locations.contact_info': 'Contact Info',
    'contact.form.subject_default': 'Get Free 7-Day Experience',
    'contact.form.error': 'An error occurred, please try again later.',
    'contact.form.success_desc': 'Thank you for your inquiry, our specialist will contact you soon.',
    'contact.form.retry': 'Send another message',
    'social.title': 'Social Media',
    'social.owner': 'Owner',
    'social.coach': 'Coach',
    'courses.reserve_btn': 'Reserve Now',
    'success.before': 'Before',
    'success.after': 'After',
    'success.duration': 'Duration',
    'coaching.philosophy_title': 'About NEO-GYM Private Coaching',
    'coaching.why_title': 'Why Choose Private Coaching?',
    'coaching.science_title': 'Scientific Training Process',
    'coaching.nutrition_title': 'Comprehensive Nutrition Guidance',
    'coaching.match_title': 'Find Your Specialist Coach',
    'coaching.category_strength': 'Strength Building',
    'coaching.category_sculpt': 'Body Sculpting',
    'coaching.category_health': 'Postnatal/Health',
    'coaching.category_special': 'Sports Performance',
    'coaching.select_title': 'Select Your Coach',
    'coaching.back': '← Back to categories',
    'coaching.note': 'Note / Requirements (Optional)',
    'ai.title': 'AI Fitness Coach',
    'ai.empty': 'Any fitness questions? Ask me! Conversations are saved automatically.',
    'ai.placeholder': 'Ask about plans or techniques...',
    'ai.clear_confirm': 'Are you sure you want to clear all chat history?',
    'ai.clear_tooltip': 'Clear chat history',
    'ai.error_response': 'I cannot answer this question right now, please try again later.',
    'ai.network_error': 'Sorry, an error occurred. Please check your connection or try again later.',
    'tools.title': 'Fitness Tools',
    'tools.bmi_title': 'BMI Calculator',
    'tools.bmi_subtitle': 'Body Assessment',
    'tools.hiit_title': 'HIIT Timer',
    'tools.hiit_subtitle': 'Interval Training',
    'tools.water_title': 'Daily Water',
    'tools.water_subtitle': 'Hydration Tracking',
    'tools.height': 'Height (cm)',
    'tools.weight': 'Weight (kg)',
    'tools.calculate_bmi': 'Calculate BMI',
    'tools.bmi_underweight': 'Underweight',
    'tools.bmi_normal': 'Normal',
    'tools.bmi_overweight': 'Overweight',
    'tools.bmi_obese1': 'Obese I',
    'tools.bmi_obese2': 'Obese II',
    'tools.bmi_obese3': 'Obese III',
    'tools.work': 'Work (sec)',
    'tools.rest': 'Rest (sec)',
    'tools.rounds': 'Rounds',
    'tools.working': '🔥🔥 Working',
    'tools.resting': '🧊🧊 Resting',
    'tools.water_goal_desc': 'Suggested daily intake 2000ml+ (approx. 8 cups)',
    'tools.water_achieved': 'Goal Reached! Well Hydrated 💧',
    'games.hurdles.instructions': 'Use Arrow Keys ↑ ↓ ← → to dodge obstacles!',
    'games.hurdles.static': 'Static',
    'games.hurdles.moving': 'Moving Up/Down',
    'games.hurdles.enter': 'Enter Level',
    'games.hurdles.level_easy': 'Easy',
    'games.hurdles.level_medium': 'Medium',
    'games.hurdles.level_hard': 'Hard',
    'games.hurdles.desc_easy': 'Few obstacles / Slow speed',
    'games.hurdles.desc_medium': 'Medium density / Normal speed',
    'games.hurdles.desc_hard': 'High density / Fast moving',
    'games.hurdles.retry': 'Retry',
    'games.hurdles.again': 'Run Again',
    'games.sprint.instructions': 'Alternate A/D to sprint! Compete with 5 elite AIs. Supports 100m & 200m distances.',
    'games.sprint.enter': 'Prepare to Race',
    'games.sprint.classic': 'Classic Neon',
    'games.sprint.volcano': 'Volcano Wastes',
    'games.sprint.jungle': 'Cyber Jungle',
    'games.sprint.deepsea': 'Deep Sea Pressure',
    'games.sprint.back_main': 'Back to Menu',
    'games.sprint.sprint_100': 'Extreme Sprint',
    'games.sprint.sprint_200': 'Endurance Burst',
    'games.sprint.reselect_env': 'Reselect Environment',
    'games.sprint.again': 'Race Again',
    'games.sprint.runner': 'AI Runner',
    'success.title': 'Success Stories',
    'success.details_title': 'Transformation Details',
    'success.cta': 'I want to book an experience plan too',
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Ready to start your path of strength? Leave your contact info and our consultants will reach out within 24 hours.',
    'contact.form.name': 'Full Name',
    'contact.form.phone': 'Phone Number',
    'contact.form.email': 'Email Address',
    'contact.form.subject': 'Inquiry Subject',
    'contact.form.message': 'Message Content',
    'contact.form.submit': 'Send Inquiry Message',
    'contact.form.success': 'Message Sent Successfully',
    'contact.info.address': 'Company Address',
    'contact.info.phone': 'Inquiry Hotline',
    'contact.info.email': 'Email',
    'contact.info.hours': 'Service Hours',
    'courses.title': 'Pro Training Courses',
    'courses.subtitle': 'Diverse high-intensity courses based on your goals, from core sculpting to power enhancement, releasing full potential.',
    'courses.target_group': 'Target Group',
    'courses.goals_title': 'Course Goals',
    'courses.details_title': 'Course Details',
    'courses.duration_label': 'Estimated Duration:',
    'courses.book_now': 'Book Experience Now'
  },
  'vi': {
    'brand': 'NEO-GYM Phòng tập thể hình',
    'nav.home': 'Trang chủ',
    'nav.about': 'Giới thiệu',
    'nav.features': 'Tính năng',
    'nav.courses': 'Khóa học',
    'nav.coaching': 'HLV Cá nhân',
    'nav.schedule': 'Lịch trình',
    'nav.locations': 'Chi nhánh',
    'nav.contact': 'Liên hệ',
    'nav.login': 'Đăng nhập',
    'hero.title': 'Vượt qua giới hạn',
    'hero.subtitle': 'Vượt qua chính mình',
    'hero.description': 'Thiết bị hàng đầu, không gian đẳng cấp, đội ngũ huấn luyện viên chuyên nghiệp.',
    'hero.start': 'Bắt đầu theo dõi',
    'hero.explore': 'Dùng thử miễn phí',
    'hero.contact': 'Liên hệ tư vấn',
    'features.title': 'Cơ sở vật chất hàng đầu',
    'features.tag': 'Cơ sở vật chất',
    'features.cardio.title': 'Khu Cardio cao cấp',
    'features.cardio.desc': 'Máy chạy bộ và xe đạp hiện đại với đồng bộ dữ liệu.',
    'features.strength.title': 'Khu kháng lực nặng',
    'features.strength.desc': 'Giá đỡ squat và thiết bị nâng tạ chuyên nghiệp.',
    'features.functional.title': 'Huấn luyện chức năng',
    'features.functional.desc': 'Sân cỏ, xe kéo và dây thừng chiến đấu.',
    'schedule.title': 'Lịch học nhóm',
    'schedule.tag': 'Lớp học nhóm',
    'schedule.mon': 'Thứ 2',
    'schedule.tue': 'Thứ 3',
    'schedule.wed': 'Thứ 4',
    'schedule.thu': 'Thứ 5',
    'schedule.fri': 'Thứ 6',
    'schedule.sat': 'Thứ 7',
    'schedule.sun': 'Chủ nhật',
    'schedule.detail': 'Xem chi tiết',
    'schedule.booking': 'Đặt lớp ngay',
    'schedule.success': 'Đặt lớp thành công!',
    'locations.title': 'Hệ thống chi nhánh',
    'locations.tag': 'Chi nhánh của chúng tôi',
    'locations.search': 'Tìm chi nhánh...',
    'locations.visit': 'Đặt lịch tham quan',
    'locations.full_schedule': 'Lịch học chi tiết',
    'coaching.title': 'Huấn luyện viên cá nhân',
    'coaching.tag': 'Huấn luyện cá nhân',
    'coaching.more': 'Tìm hiểu thêm',
    'coaching.find': 'Tìm huấn luyện viên',
    'coaching.reserve': 'Đặt lịch tư vấn',
    'footer.rights': '© 2026 NEO-GYM. Bảo lưu mọi quyền.',
    'common.name': 'Họ tên',
    'common.phone': 'Số điện thoại',
    'common.email': 'Email',
    'common.submit': 'Xác nhận gửi',
    'schedule.booking_title': 'Thông tin đặt chỗ',
    'schedule.booking_success': 'Đặt lớp thành công!',
    'schedule.booking_received': 'Chúng tôi đã nhận được yêu cầu đặt chỗ của bạn.',
    'schedule.instructor': 'Huấn luyện viên',
    'schedule.level': 'Cấp độ đề xuất',
    'schedule.intro': 'Giới thiệu khóa học',
    'locations.booking_title': 'Đặt lịch tham quan miễn phí',
    'locations.booking_success': 'Đặt lịch tham quan thành công!',
    'locations.booking_received': 'Chuyên viên sẽ liên hệ với bạn trong vòng 24 giờ.',
    'locations.details_btn': 'Xem chi tiết chi nhánh',
    'locations.facilities': 'Tiện nghi',
    'locations.contact_info': 'Thông tin liên hệ',
    'contact.form.subject_default': 'Nhận gói trải nghiệm 7 ngày miễn phí',
    'contact.form.error': 'Đã xảy ra lỗi, vui lòng thử lại sau.',
    'contact.form.success_desc': 'Cảm ơn bạn đã quan tâm, chuyên viên sẽ liên hệ với bạn sớm nhất.',
    'contact.form.retry': 'Gửi một tin nhắn khác',
    'social.title': 'Mạng xã hội',
    'social.owner': 'Chủ sở hữu',
    'social.coach': 'Huấn luyện viên',
    'courses.reserve_btn': 'Đặt chỗ ngay',
    'success.before': 'Trước',
    'success.after': 'Sau',
    'success.duration': 'Thời gian',
    'coaching.philosophy_title': 'Về HLV cá nhân tại NEO-GYM',
    'coaching.why_title': 'Tại sao chọn HLV cá nhân?',
    'coaching.science_title': 'Quy trình đào tạo khoa học',
    'coaching.nutrition_title': 'Hướng dẫn dinh dưỡng toàn diện',
    'coaching.match_title': 'Tìm huấn luyện viên phù hợp',
    'coaching.category_strength': 'Tăng cường sức mạnh',
    'coaching.category_sculpt': 'Điêu khắc hình thể',
    'coaching.category_health': 'Sau sinh/Sức khỏe',
    'coaching.category_special': 'Tăng cường thể thao chuyên biệt',
    'coaching.select_title': 'Chọn huấn luyện viên của bạn',
    'coaching.back': '← Quay lại danh mục',
    'coaching.note': 'Ghi chú / Yêu cầu (Tùy chọn)',
    'ai.title': 'Huấn luyện viên AI',
    'ai.empty': 'Có bất kỳ câu hỏi nào về thể dục? Hãy hỏi tôi! Các cuộc hội thoại được lưu tự động.',
    'ai.placeholder': 'Hỏi về kế hoạch hoặc kỹ thuật...',
    'ai.clear_confirm': 'Bạn có chắc chắn muốn xóa tất cả lịch sử trò chuyện không?',
    'ai.clear_tooltip': 'Xóa lịch sử trò chuyện',
    'ai.error_response': 'Tôi không thể trả lời câu hỏi này lúc này, vui lòng thử lại sau.',
    'ai.network_error': 'Xin lỗi, đã xảy ra lỗi. Vui lòng kiểm tra kết nối của bạn hoặc thử lại sau.',
    'tools.title': 'Công cụ thể dục',
    'tools.bmi_title': 'Máy tính BMI',
    'tools.bmi_subtitle': 'Đánh giá cơ thể',
    'tools.hiit_title': 'Đồng hồ HIIT',
    'tools.hiit_subtitle': 'Tập luyện ngắt quãng',
    'tools.water_title': 'Nước hàng ngày',
    'tools.water_subtitle': 'Theo dõi hydrat hóa',
    'tools.height': 'Chiều cao (cm)',
    'tools.weight': 'Cân nặng (kg)',
    'tools.calculate_bmi': 'Tính chỉ số BMI',
    'tools.bmi_underweight': 'Thiếu cân',
    'tools.bmi_normal': 'Bình thường',
    'tools.bmi_overweight': 'Thừa cân',
    'tools.bmi_obese1': 'Béo phì độ 1',
    'tools.bmi_obese2': 'Béo phì độ 2',
    'tools.bmi_obese3': 'Béo phì độ 3',
    'tools.work': 'Làm việc (giây)',
    'tools.rest': 'Nghỉ ngơi (giây)',
    'tools.rounds': 'Số vòng',
    'tools.working': '🔥🔥 Đang tập',
    'tools.resting': '🧊🧊 Đang nghỉ',
    'tools.water_goal_desc': 'Khuyên dùng hàng ngày trên 2000ml (khoảng 8 ly)',
    'tools.water_achieved': 'Đạt được mục tiêu! Đã cung cấp đủ nước 💧',
    'games.hurdles.instructions': 'Sử dụng phím mũi tên ↑ ↓ ← → để né tránh vật cản!',
    'games.hurdles.static': 'Tĩnh',
    'games.hurdles.moving': 'Di chuyển lên/xuống',
    'games.hurdles.enter': 'Vào cấp độ',
    'games.hurdles.level_easy': 'Dễ',
    'games.hurdles.level_medium': 'Vừa',
    'games.hurdles.level_hard': 'Khó',
    'games.hurdles.desc_easy': 'Ít vật cản / Tốc độ chậm',
    'games.hurdles.desc_medium': 'Mật độ trung bình / Tốc độ chuẩn',
    'games.hurdles.desc_hard': 'Mật độ cao / Di chuyển nhanh',
    'games.hurdles.retry': 'Thử lại',
    'games.hurdles.again': 'Chạy lại',
    'games.sprint.instructions': 'Nhấn luân phiên A/D để chạy nước rút! Thi đấu với 5 AI ưu tú. Hỗ trợ 100m & 200m.',
    'games.sprint.enter': 'Chuẩn bị thi đấu',
    'games.sprint.classic': 'Neon cổ điển',
    'games.sprint.volcano': 'Hoang mạc núi lửa',
    'games.sprint.jungle': 'Rừng rậm không gian mạng',
    'games.sprint.deepsea': 'Áp suất biển sâu',
    'games.sprint.back_main': 'Quay lại menu',
    'games.sprint.sprint_100': 'Chạy nước rút cực hạn',
    'games.sprint.sprint_200': 'Bùng nổ sức bền',
    'games.sprint.reselect_env': 'Chọn lại môi trường',
    'games.sprint.again': 'Thi đấu lại',
    'games.sprint.runner': 'Người chạy AI',
    'success.title': 'Câu chuyện thành công',
    'success.details_title': 'Chi tiết chuyển đổi',
    'success.cta': 'Tôi cũng muốn đặt lịch trải nghiệm',
    'contact.title': 'Liên hệ với chúng tôi',
    'contact.subtitle': 'Sẵn sàng bắt đầu con đường sức mạnh của bạn? Để lại thông tin và cố vấn của chúng tôi sẽ liên hệ trong vòng 24 giờ.',
    'contact.form.name': 'Họ và tên',
    'contact.form.phone': 'Số điện thoại',
    'contact.form.email': 'Địa chỉ Email',
    'contact.form.subject': 'Chủ đề tư vấn',
    'contact.form.message': 'Nội dung tin nhắn',
    'contact.form.submit': 'Gửi tin nhắn tư vấn',
    'contact.form.success': 'Gửi tin nhắn thành công',
    'contact.info.address': 'Địa chỉ công ty',
    'contact.info.phone': 'Hotline tư vấn',
    'contact.info.email': 'Email',
    'contact.info.hours': 'Giờ phục vụ',
    'courses.title': 'Khóa học đào tạo chuyên nghiệp',
    'courses.subtitle': 'Các khóa học cường độ cao đa dạng dựa trên mục tiêu của bạn, từ điêu khắc cốt lõi đến tăng cường sức mạnh.',
    'courses.target_group': 'Nhóm mục tiêu',
    'courses.goals_title': 'Mục tiêu khóa học',
    'courses.details_title': 'Chi tiết khóa học',
    'courses.duration_label': 'Thời gian dự kiến:',
    'courses.book_now': 'Đặt lịch trải nghiệm ngay'
  },
  'id': {
    'brand': 'NEO-GYM Pusat Kebugaran',
    'nav.home': 'Beranda',
    'nav.about': 'Tentang',
    'nav.features': 'Fitur',
    'nav.courses': 'Kursus',
    'nav.coaching': 'Pelatih',
    'nav.schedule': 'Jadwal',
    'nav.locations': 'Lokasi',
    'nav.contact': 'Kontak',
    'nav.login': 'Masuk',
    'hero.title': 'Lampaui Batas Anda',
    'hero.subtitle': 'LAMPAUI DIRIMU',
    'hero.description': 'Peralatan kelas atas, ruang terbaik, tim pelatih profesional, lahir untuk evolusi Anda.',
    'hero.start': 'Mulai Pelacakan',
    'hero.explore': 'Coba Gratis',
    'hero.contact': 'Hubungi Konselor',
    'features.title': 'Fasilitas Utama',
    'features.tag': 'Fasilitas Utama',
    'features.cardio.title': 'Kardiovaskular Lanjut',
    'features.cardio.desc': 'Treadmill dan sepeda kelas atas dengan sinkronisasi data.',
    'features.strength.title': 'Resistensi Berat',
    'features.strength.desc': 'Rak squat ganda dan peralatan angkat beban profesional.',
    'features.functional.title': 'Pelatihan Fungsional',
    'features.functional.desc': 'Rumput, kereta luncur, dan tali tempur.',
    'schedule.title': 'Jadwal Kelas',
    'schedule.tag': 'Kelas Grup',
    'schedule.mon': 'Sen',
    'schedule.tue': 'Sel',
    'schedule.wed': 'Rab',
    'schedule.thu': 'Kam',
    'schedule.fri': 'Jum',
    'schedule.sat': 'Sab',
    'schedule.sun': 'Min',
    'schedule.detail': 'Lihat Detail',
    'schedule.booking': 'Pesan Kelas Sekarang',
    'schedule.success': 'Pemesanan Berhasil!',
    'locations.title': 'Cabang Nasional',
    'locations.tag': 'Lokasi Kami',
    'locations.search': 'Cari cabang...',
    'locations.visit': 'Pesan Kunjungan Gratis',
    'locations.full_schedule': 'Jadwal Lengkap',
    'coaching.title': 'Pelatih Pribadi',
    'coaching.tag': 'Pelatihan Pribadi',
    'coaching.more': 'Pelajari Lebih Lanjut',
    'coaching.find': 'Cari Pelatih',
    'coaching.reserve': 'Reservasi Konsultasi',
    'footer.rights': '© 2026 NEO-GYM. Seluruh hak cipta dilindungi.',
    'common.name': 'Nama',
    'common.phone': 'Telepon',
    'common.email': 'Email',
    'common.submit': 'Kirim',
    'schedule.booking_title': 'Informasi Pemesanan',
    'schedule.booking_success': 'Kelas Berhasil Dipesan!',
    'schedule.booking_received': 'Kami telah menerima permintaan pemesanan Anda.',
    'schedule.instructor': 'Instruktur',
    'schedule.level': 'Tingkat',
    'schedule.intro': 'Pendahuluan',
    'locations.booking_title': 'Pesan Kunjungan Gratis',
    'locations.booking_success': 'Kunjungan Berhasil Dipesan!',
    'locations.booking_received': 'Spesialis kami akan menghubungi Anda dalam 24 jam.',
    'locations.details_btn': 'Lihat Detail Cabang',
    'locations.facilities': 'Fasilitas',
    'locations.contact_info': 'Info Kontak',
    'contact.form.subject_default': 'Dapatkan Pengalaman Gratis 7 Hari',
    'contact.form.error': 'Terjadi kesalahan, silakan coba lagi nanti.',
    'contact.form.success_desc': 'Terima kasih atas pertanyaan Anda, spesialis kami akan segera menghubungi Anda.',
    'contact.form.retry': 'Kirim pesan lain',
    'social.title': 'Media Sosial',
    'social.owner': 'Pemilik',
    'social.coach': 'Pelatih',
    'courses.reserve_btn': 'Reservasi Sekarang',
    'success.before': 'Sebelum',
    'success.after': 'Sesudah',
    'success.duration': 'Durasi',
    'coaching.philosophy_title': 'Tentang Pelatih Pribadi NEO-GYM',
    'coaching.why_title': 'Mengapa Memilih Pelatih Pribadi?',
    'coaching.science_title': 'Proses Pelatihan Ilmiah',
    'coaching.nutrition_title': 'Panduan Nutrisi Komprehensif',
    'coaching.match_title': 'Temukan Pelatih Spesialis Anda',
    'coaching.category_strength': 'Membangun Kekuatan',
    'coaching.category_sculpt': 'Membentuk Tubuh',
    'coaching.category_health': 'Pascapersalinan/Kesehatan',
    'coaching.category_special': 'Performa Olahraga',
    'coaching.select_title': 'Pilih Pelatih Anda',
    'coaching.back': '← Kembali ke kategori',
    'coaching.note': 'Catatan / Persyaratan (Opsional)',
    'ai.title': 'Pelatih Kebugaran AI',
    'ai.empty': 'Ada pertanyaan kebugaran? Tanya saya! Percakapan disimpan secara otomatis.',
    'ai.placeholder': 'Tanya tentang rencana atau teknik...',
    'ai.clear_confirm': 'Apakah Anda yakin ingin menghapus semua riwayat obrolan?',
    'ai.clear_tooltip': 'Hapus riwayat obrolan',
    'ai.error_response': 'Saya tidak dapat menjawab pertanyaan ini sekarang, silakan coba lagi nanti.',
    'ai.network_error': 'Maaf, terjadi kesalahan. Silakan periksa koneksi Anda atau coba lagi nanti.',
    'tools.title': 'Alat Kebugaran',
    'tools.bmi_title': 'Kalkulator BMI',
    'tools.bmi_subtitle': 'Asesmen Tubuh',
    'tools.hiit_title': 'Timer HIIT',
    'tools.hiit_subtitle': 'Latihan Interval',
    'tools.water_title': 'Air Harian',
    'tools.water_subtitle': 'Pelacakan Hidrasi',
    'tools.height': 'Tinggi (cm)',
    'tools.weight': 'Berat (kg)',
    'tools.calculate_bmi': 'Hitung BMI',
    'tools.bmi_underweight': 'Berat Kurang',
    'tools.bmi_normal': 'Normal',
    'tools.bmi_overweight': 'Kelebihan Berat',
    'tools.bmi_obese1': 'Obesitas I',
    'tools.bmi_obese2': 'Obesitas II',
    'tools.bmi_obese3': 'Obesitas III',
    'tools.work': 'Kerja (det)',
    'tools.rest': 'Istirahat (det)',
    'tools.rounds': 'Putaran',
    'tools.working': '🔥🔥 Sedang Bekerja',
    'tools.resting': '🧊🧊 Sedang Istirahat',
    'tools.water_goal_desc': 'Asupan harian yang disarankan 2000ml+ (sekitar 8 gelas)',
    'tools.water_achieved': 'Target Tercapai! Terhidrasi Baik 💧',
    'games.hurdles.instructions': 'Gunakan Tombol Panah ↑ ↓ ← → untuk menghindari rintangan!',
    'games.hurdles.static': 'Statis',
    'games.hurdles.moving': 'Bergerak Naik/Turun',
    'games.hurdles.enter': 'Masuk Level',
    'games.hurdles.level_easy': 'Mudah',
    'games.hurdles.level_medium': 'Sedang',
    'games.hurdles.level_hard': 'Sulit',
    'games.hurdles.desc_easy': 'Sedikit rintangan / Kecepatan lambat',
    'games.hurdles.desc_medium': 'Kepadatan sedang / Kecepatan standar',
    'games.hurdles.desc_hard': 'Kepadatan tinggi / Bergerak cepat',
    'games.hurdles.retry': 'Coba Lagi',
    'games.hurdles.again': 'Lari Lagi',
    'games.sprint.instructions': 'Gunakan A/D secara bergantian untuk lari cepat! Bersaing dengan 5 AI elit. Mendukung jarak 100m & 200m.',
    'games.sprint.enter': 'Bersiap Balapan',
    'games.sprint.classic': 'Neon Klasik',
    'games.sprint.volcano': 'Gurun Vulkanik',
    'games.sprint.jungle': 'Hutan Siber',
    'games.sprint.deepsea': 'Tekanan Laut Dalam',
    'games.sprint.back_main': 'Kembali ke Menu',
    'games.sprint.sprint_100': 'Sprint Ekstrem',
    'games.sprint.sprint_200': 'Ledakan Daya Tahan',
    'games.sprint.reselect_env': 'Pilih Ulang Lingkungan',
    'games.sprint.again': 'Balapan Lagi',
    'games.sprint.runner': 'Pelari AI',
    'success.title': 'Kisah Sukses',
    'success.details_title': 'Detail Transformasi',
    'success.cta': 'Saya juga ingin memesan rencana pengalaman',
    'contact.title': 'Hubungi Kami',
    'contact.subtitle': 'Siap untuk memulai jalan kekuatan Anda? Tinggalkan info kontak Anda dan konsultan kami akan menghubungi dalam 24 jam.',
    'contact.form.name': 'Nama Lengkap',
    'contact.form.phone': 'Nomor Telepon',
    'contact.form.email': 'Alamat Email',
    'contact.form.subject': 'Subjek Pertanyaan',
    'contact.form.message': 'Isi Pesan',
    'contact.form.submit': 'Kirim Pesan Pertanyaan',
    'contact.form.success': 'Pesan Berhasil Terkirim',
    'contact.info.address': 'Alamat Perusahaan',
    'contact.info.phone': 'Hotline Pertanyaan',
    'contact.info.email': 'Email',
    'contact.info.hours': 'Jam Layanan',
    'courses.title': 'Kursus Pelatihan Pro',
    'courses.subtitle': 'Beragam kursus intensitas tinggi berdasarkan tujuan Anda, dari pemahatan inti hingga peningkatan daya.',
    'courses.target_group': 'Grup Target',
    'courses.goals_title': 'Tujuan Kursus',
    'courses.details_title': 'Detail Kursus',
    'courses.duration_label': 'Estimasi Durasi:',
    'courses.book_now': 'Pesan Pengalaman Sekarang'
  },
  'ja': {
    'brand': 'NEO-GYM プロフィットネス',
    'nav.home': 'ホーム',
    'nav.about': 'について',
    'nav.features': '特徴',
    'nav.courses': 'コース',
    'nav.coaching': 'コーチ',
    'nav.schedule': 'スケジュール',
    'nav.locations': '店舗',
    'nav.contact': 'お問い合わせ',
    'nav.login': 'ログイン',
    'hero.title': '限界を超えろ',
    'hero.subtitle': '自分を越えろ',
    'hero.description': '最先端の設備、究極の空間、プロのコーチ陣。あなたの進化のために。',
    'hero.start': '追跡開始',
    'hero.explore': '無料体験',
    'hero.contact': 'カウンセリング予約',
    'features.title': '最高の施設',
    'features.tag': '最高の施設',
    'features.cardio.title': '高機能有酸素エリア',
    'features.cardio.desc': 'リアルタイムデータ同期対応のランニングマシン完備。',
    'features.strength.title': '高重量負荷エリア',
    'features.strength.desc': '多数のスクワットラックとプロ仕様のリフティング機材。',
    'features.functional.title': 'ファンクショナルトレーニング',
    'features.functional.desc': '人工芝、スレッド、バトルロープで機能性を向上。',
    'schedule.title': 'クラススケジュール',
    'schedule.tag': 'グループクラス',
    'schedule.mon': '月',
    'schedule.tue': '火',
    'schedule.wed': '水',
    'schedule.thu': '木',
    'schedule.fri': '金',
    'schedule.sat': '土',
    'schedule.sun': '日',
    'schedule.detail': '詳細を見る',
    'schedule.booking': '今すぐ予約',
    'schedule.success': '予約が完了しました！',
    'locations.title': '全国の拠点',
    'locations.tag': '各店舗',
    'locations.search': '店舗を探す...',
    'locations.visit': '無料見學予約',
    'locations.full_schedule': '全スケジュール',
    'coaching.title': 'パーソナルトレーニング',
    'coaching.tag': 'パーソナル',
    'coaching.more': '詳細はこちら',
    'coaching.find': 'トレーナーを探す',
    'coaching.reserve': '体験・相談予約',
    'footer.rights': '© 2026 NEO-GYM. All rights reserved.',
    'common.name': '氏名',
    'common.phone': '電話番号',
    'common.email': 'メール',
    'common.submit': '送信する',
    'schedule.booking_title': '予約情報の入力',
    'schedule.booking_success': 'クラスの予約が完了しました！',
    'schedule.booking_received': '予約リクエストを受け付けました。',
    'schedule.instructor': '担当インストラクター',
    'schedule.level': '推奨レベル',
    'schedule.intro': 'コース紹介',
    'locations.booking_title': '無料見学予約',
    'locations.booking_success': '見学予約が完了しました！',
    'locations.booking_received': '担当者より24時間以内にご連絡いたします。',
    'locations.details_btn': '店舗詳細を見る',
    'locations.facilities': '館内施設',
    'locations.contact_info': '連絡先情報',
    'contact.form.subject_default': '無料7日間体験プランを申し込む',
    'contact.form.error': 'エラーが発生しました。後でもう一度お試しください。',
    'contact.form.success_desc': 'お問い合わせありがとうございます。担当者より折り返しご連絡いたします。',
    'contact.form.retry': '別のメッセージを送る',
    'social.title': 'ソーシャルメディア',
    'social.owner': 'オーナー',
    'social.coach': 'コーチ',
    'courses.reserve_btn': '今すぐ予約',
    'success.before': 'Before',
    'success.after': 'After',
    'success.duration': '期間',
    'coaching.philosophy_title': 'NEO-GYMのパーソナルトレーニングについて',
    'coaching.why_title': 'なぜパーソナルトレーナーを選ぶのか？',
    'coaching.science_title': '科学的なトレーニングプロセス',
    'coaching.nutrition_title': '包括的な栄養指導',
    'coaching.match_title': 'あなたの専属コーチを見つける',
    'coaching.category_strength': '筋力アップ',
    'coaching.category_sculpt': 'ボディメイキング',
    'coaching.category_health': '産後・ヘルスケア',
    'coaching.category_special': '競技力向上',
    'coaching.select_title': 'コーチを選択',
    'coaching.back': '← カテゴリに戻る',
    'coaching.note': '備考 / ご要望（任意）',
    'ai.title': 'AI フィットネスコーチ',
    'ai.empty': 'フィットネスに関する質問はありますか？私に聞いてください！会話は自動的に保存されます。',
    'ai.placeholder': 'プランやテクニックについて聞く...',
    'ai.clear_confirm': 'すべてのチャット履歴を消去してもよろしいですか？',
    'ai.clear_tooltip': 'チャット履歴を消去',
    'ai.error_response': '現在、この質問にはお答えできません。後でもう一度お試しください。',
    'ai.network_error': '申し訳ありません。エラーが発生しました。接続を確認するか、後でもう一度お試しください。',
    'tools.title': 'フィットネスツール',
    'tools.bmi_title': 'BMI 計算機',
    'tools.bmi_subtitle': '体態評価',
    'tools.hiit_title': 'HIIT タイマー',
    'tools.hiit_subtitle': 'インターバルトレーニング',
    'tools.water_title': '毎日の飲水',
    'tools.water_subtitle': '水分追跡',
    'tools.height': '身長 (cm)',
    'tools.weight': '体重 (kg)',
    'tools.calculate_bmi': 'BMIを計算する',
    'tools.bmi_underweight': '低体重',
    'tools.bmi_normal': '標準',
    'tools.bmi_overweight': '肥満気味',
    'tools.bmi_obese1': '肥満（1度）',
    'tools.bmi_obese2': '肥満（2度）',
    'tools.bmi_obese3': '肥満（3度）',
    'tools.work': 'ワーク（秒）',
    'tools.rest': 'レスト（秒）',
    'tools.rounds': 'ラウンド数',
    'tools.working': '🔥🔥 トレーニング中',
    'tools.resting': '🧊🧊 休憩中',
    'tools.water_goal_desc': '1日2000ml以上の水分摂取（約8杯）を推奨します',
    'tools.water_achieved': '目標達成！水分補給はバッチリです 💧',
    'games.hurdles.instructions': '矢印キー ↑ ↓ ← → を使って障害物を避けよう！',
    'games.hurdles.static': '固定',
    'games.hurdles.moving': '上下移動',
    'games.hurdles.enter': 'レベルに入る',
    'games.hurdles.level_easy': '簡単',
    'games.hurdles.level_medium': '普通',
    'games.hurdles.level_hard': '難しい',
    'games.hurdles.desc_easy': '障害物少なめ / 低速',
    'games.hurdles.desc_medium': '標準密度 / 標準速度',
    'games.hurdles.desc_hard': '高密度 / 高速',
    'games.hurdles.retry': 'リトライ',
    'games.hurdles.again': 'もう一度走る',
    'games.sprint.instructions': 'AキーとDキーを交互に叩いてダッシュ！5人のエリートAIと競い合おう。100mと200mに対応。',
    'games.sprint.enter': '準備開始',
    'games.sprint.classic': 'クラシックネオン',
    'games.sprint.volcano': 'ボルケーノ原野',
    'games.sprint.jungle': 'サイバージャングル',
    'games.sprint.deepsea': 'ディープシー・プレッシャー',
    'games.sprint.back_main': 'メインメニューに戻る',
    'games.sprint.sprint_100': 'エクストリーム・スプリント',
    'games.sprint.sprint_200': 'エンデュランス・バースト',
    'games.sprint.reselect_env': '環境を再選択',
    'games.sprint.again': 'もう一度レース',
    'games.sprint.runner': 'AIランナー',
    'success.title': '成功事例',
    'success.details_title': '変遷の詳細',
    'success.cta': '体験プランを予約する',
    'contact.title': 'お問い合わせ',
    'contact.subtitle': '強者への道を歩む準備はできましたか？連絡先をご記入ください。24時間以内に専門アドバイザーがご連絡いたします。',
    'contact.form.name': 'お名前',
    'contact.form.phone': '電話番号',
    'contact.form.email': 'メールアドレス',
    'contact.form.subject': 'お問い合わせ件名',
    'contact.form.message': 'メッセージ内容',
    'contact.form.submit': 'お問い合わせを送信',
    'contact.form.success': '送信が完了しました',
    'contact.info.address': '会社住所',
    'contact.info.phone': '相談専用ダイヤル',
    'contact.info.email': 'メール',
    'contact.info.hours': 'サービス時間',
    'courses.title': 'プロトレーニングコース',
    'courses.subtitle': 'コアの彫刻から瞬発力の向上まで、目標に合わせた多様な高強度プログラムを用意しています。',
    'courses.target_group': '対象者',
    'courses.goals_title': 'トレーニング目標',
    'courses.details_title': 'コース詳細',
    'courses.duration_label': '予想時間：',
    'courses.book_now': '今すぐ体験予約'
  },
  'ko': {
    'brand': 'NEO-GYM 프로 피트니스',
    'nav.home': '홈',
    'nav.about': '소개',
    'nav.features': '특징',
    'nav.courses': '코스',
    'nav.coaching': '코칭',
    'nav.schedule': '스케줄',
    'nav.locations': '지점',
    'nav.contact': '문의하기',
    'nav.login': '로그인',
    'hero.title': '한계를 넘어라',
    'hero.subtitle': '자신을 초월하라',
    'hero.description': '최고급 장비, 궁극의 공간, 전문 코치진. 당신의 진화를 위해 탄생했습니다.',
    'hero.start': '기록 시작',
    'hero.explore': '무료 체험',
    'hero.contact': '상담 예약',
    'features.title': '최고의 시설',
    'features.tag': '최고의 시설',
    'features.cardio.title': '고급 유산소 구역',
    'features.cardio.desc': '실시간 데이터 동기화가 가능한 프리미엄 유산소 장비.',
    'features.strength.title': '중량 저항 구역',
    'features.strength.desc': '다양한 스쿼트 랙과 전문 파워리프팅 장비.',
    'features.functional.title': '기능성 트레이닝',
    'features.functional.desc': '인조잔디, 슬레드, 배틀로프로 기능성 강화.',
    'schedule.title': '그룹 클래스 시간표',
    'schedule.tag': '그룹 클래스',
    'schedule.mon': '월',
    'schedule.tue': '화',
    'schedule.wed': '수',
    'schedule.thu': '목',
    'schedule.fri': '금',
    'schedule.sat': '토',
    'schedule.sun': '일',
    'schedule.detail': '자세히 보기',
    'schedule.booking': '지금 예약하기',
    'schedule.success': '예약이 완료되었습니다!',
    'locations.title': '전국 지점 안내',
    'locations.tag': '지점 안내',
    'locations.search': '지점 검색...',
    'locations.visit': '무료 방문 예약',
    'locations.full_schedule': '전체 시간표',
    'coaching.title': '개인 트레이닝',
    'coaching.tag': '퍼스널 트레이닝',
    'coaching.more': '자세히 보기',
    'coaching.find': '트레이너 찾기',
    'coaching.reserve': '상담 예약하기',
    'footer.rights': '© 2026 NEO-GYM. All rights reserved.',
    'common.name': '이름',
    'common.phone': '전화번호',
    'common.email': '이메일',
    'common.submit': '제출하기',
    'schedule.booking_title': '예약 정보 입력',
    'schedule.booking_success': '클래스 예약이 완료되었습니다!',
    'schedule.booking_received': '예약 요청이 접수되었습니다.',
    'schedule.instructor': '담당 강사',
    'schedule.level': '권장 레벨',
    'schedule.intro': '코스 소개',
    'locations.booking_title': '무료 방문 예약',
    'locations.booking_success': '방문 예약이 완료되었습니다!',
    'locations.booking_received': '담당자가 24시간 이내에 연락드리겠습니다.',
    'locations.details_btn': '지점 상세 보기',
    'locations.facilities': '지점 시설',
    'locations.contact_info': '연락처 정보',
    'contact.form.subject_default': '무료 7일 체험 플랜 받기',
    'contact.form.error': '오류가 발생했습니다. 나중에 다시 시도해 주세요.',
    'contact.form.success_desc': '문의해 주셔서 감사합니다. 담당자가 곧 연락드리겠습니다.',
    'contact.form.retry': '다른 메시지 보내기',
    'social.title': '소셜 미디어',
    'social.owner': '대표',
    'social.coach': '코치',
    'courses.reserve_btn': '지금 예약하기',
    'success.before': 'Before',
    'success.after': 'After',
    'success.duration': '기간',
    'coaching.philosophy_title': 'NEO-GYM 퍼스널 트레이닝 소개',
    'coaching.why_title': '왜 퍼스널 트레이너를 선택해야 할까요?',
    'coaching.science_title': '과학적인 트레이닝 프로세스',
    'coaching.nutrition_title': '종괄적인 영양 지도',
    'coaching.match_title': '나만의 전담 코치 찾기',
    'coaching.category_strength': '근력 증진',
    'coaching.category_sculpt': '체형 조각',
    'coaching.category_health': '산후/건강 관리',
    'coaching.category_special': '전문 운동 강화',
    'coaching.select_title': '코치 선택하기',
    'coaching.back': '← 카테고리로 돌아가기',
    'coaching.note': '비고 / 요청 사항 (선택)',
    'ai.title': 'AI 운동 코치',
    'ai.empty': '운동에 대해 궁금한 점이 있으신가요? 제게 물어보세요! 대화는 자동으로 저장됩니다.',
    'ai.placeholder': '계획이나 테크닉에 대해 물어보세요...',
    'ai.clear_confirm': '모든 채팅 기록을 삭제하시겠습니까?',
    'ai.clear_tooltip': '채팅 기록 삭제',
    'ai.error_response': '지금은 질문에 답할 수 없습니다. 나중에 다시 시도해 주세요.',
    'ai.network_error': '죄송합니다. 오류가 발생했습니다. 연결을 확인하거나 나중에 다시 시도해 주세요.',
    'tools.title': '피트니스 보조 도구',
    'tools.bmi_title': 'BMI 계산기',
    'tools.bmi_subtitle': '체형 평가',
    'tools.hiit_title': 'HIIT 타이머',
    'tools.hiit_subtitle': '인터벌 트레이닝',
    'tools.water_title': '오늘의 수분',
    'tools.water_subtitle': '수분 추적',
    'tools.height': '키 (cm)',
    'tools.weight': '몸무게 (kg)',
    'tools.calculate_bmi': 'BMI 지수 계산기',
    'tools.bmi_underweight': '저체중',
    'tools.bmi_normal': '정상 범위',
    'tools.bmi_overweight': '과체중',
    'tools.bmi_obese1': '경도 비만',
    'tools.bmi_obese2': '중등도 비만',
    'tools.bmi_obese3': '고도 비만',
    'tools.work': '운동 (초)',
    'tools.rest': '휴식 (초)',
    'tools.rounds': '세트 수',
    'tools.working': '🔥🔥 운동 중',
    'tools.resting': '🧊🧊 휴식 중',
    'tools.water_goal_desc': '하루 2000ml 이상의 수분 섭취를 권장합니다 (약 8잔)',
    'tools.water_achieved': '목표 달성! 수분 충전 완료 💧',
    'games.hurdles.instructions': '방향키 ↑ ↓ ← → 를 사용하여 장애물을 피하세요!',
    'games.hurdles.static': '고정형',
    'games.hurdles.moving': '상하 이동형',
    'games.hurdles.enter': '레벨 시작',
    'games.hurdles.level_easy': '쉬움',
    'games.hurdles.level_medium': '보통',
    'games.hurdles.level_hard': '어려움',
    'games.hurdles.desc_easy': '장애물 적음 / 느린 속도',
    'games.hurdles.desc_medium': '보통 밀도 / 표준 속도',
    'games.hurdles.desc_hard': '높은 밀도 / 빠른 속도',
    'games.hurdles.retry': '다시 시도',
    'games.hurdles.again': '다시 달리기',
    'games.sprint.instructions': 'A/D 키를 번갈아 눌러 질주하세요! 5명의 엘리트 AI와 경쟁하세요. 100m 및 200m 지원.',
    'games.sprint.enter': '준비하기',
    'games.sprint.classic': '클래식 네온',
    'games.sprint.volcano': '화산 황무지',
    'games.sprint.jungle': '사이버 정글',
    'games.sprint.deepsea': '심해 어비스',
    'games.sprint.back_main': '메인 메뉴로 돌아가기',
    'games.sprint.sprint_100': '익스트림 스프린트',
    'games.sprint.sprint_200': '지구력 폭발',
    'games.sprint.reselect_env': '환경 다시 선택하기',
    'games.sprint.again': '다시 경기하기',
    'games.sprint.runner': 'AI 러너',
    'success.title': '성공 사례',
    'success.details_title': '변화 상세 내용',
    'success.cta': '나도 체험 플랜 예약하기',
    'contact.title': '문의하기',
    'contact.subtitle': '강자의 길을 시작할 준비가 되셨나요? 연락처를 남겨주시면 24시간 이내에 전문 상담원이 연락드리겠습니다.',
    'contact.form.name': '이름',
    'contact.form.phone': '연락처',
    'contact.form.email': '이메일 주소',
    'contact.form.subject': '문의 주제',
    'contact.form.message': '메시지 내용',
    'contact.form.submit': '문의 메시지 전송',
    'contact.form.success': '메시지가 전송되었습니다',
    'contact.info.address': '회사 주소',
    'contact.info.phone': '상담 전용 전화',
    'contact.info.email': '이메일',
    'contact.info.hours': '서비스 시간',
    'courses.title': '전문 트레이닝 코스',
    'courses.subtitle': '코어 강화부터 폭발적인 힘 향상까지, 목표에 맞는 다양한 고강도 코스를 제공합니다.',
    'courses.target_group': '대상',
    'courses.goals_title': '수업 목표',
    'courses.details_title': '수업 상세',
    'courses.duration_label': '예상 소요 시간:',
    'courses.book_now': '지금 체험 예약하기'
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [currentLang, setCurrentLang] = useState<Language>(LANGUAGES[0]);

  const setLanguage = (code: LanguageCode) => {
    const lang = LANGUAGES.find(l => l.code === code);
    if (lang) setCurrentLang(lang);
  };

  const t = (key: string): string => {
    return TRANSLATIONS[currentLang.code][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLang, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
